### ISSUE TITLE
Crashes on Xiaomi/Huawei devices

### ISSUE THREAD

**Issue by JurjenBiewenga** [google/play-unity-plugins#100]
Hi,

Recently we released a new version of our game with install time asset bundles, this seems to work fine on almost all devices however we've noticed an increase in crashes on Xiaomi and Huawei devices. These crashes seem to be because the bundles don't exist or can't be loaded for some other reason, we currently don't have data proving this though.
We're suspecting that these devices don't come shipped with GP and as such might be getting our app through other means or GP being installed through other means. 
Have you seen similar issues or knowledge why these crashes might be occurring?

Thanks,
Jurjen

**Comment by jamcohen** [comment]
Hi Jurjen,

I'm not aware of any crash issues specific to Xiaomi and Huawei devices.
Are there any logs you can share? Feel free to post them here or email us at play-unity-plugin-support@googlegroups.com

When users install the app via the Google Play store, the store will install both the asset bundles and the base apk.
If users are installing the app through other means, they're likely only installing the base apk which would indeed lead to the issues you mention.

**Comment by JurjenBiewenga** [comment]
Hey @jamcohen,

Thank you for confirming my suspicions.

We're currently not able to reproduce the issue locally however we've got some players that have contacted our support and we're trying to verify how they installed our app. I'll update here if we get a response, keep in mind that we might not get a response since users might not want to admit they downloaded the app through third party websites.

Regarding the logs, as we only have crashlytics logs from live users we're currently not prepared to share these logs.

**Comment by JurjenBiewenga** [comment]
Hi,

We've thought of a temporary fix/work around, if preloaded bundles can't be loaded we'll still download them however we're still investigating the actual cause of the issue. Currently it seems that we have users that did install it through google play and are having this issue, this is both verified by the user and that it's unlikely that they're able to make a purchase through the game without having access to GAPPS.

**Comment by JurjenBiewenga** [comment]
Most of the exceptions are now coming from Xiaomi devices, a large part from MIUI RU but also quite a few from MIUI Global. About half of our sample set seems to be able to recover after a few restarts (potential reinstalls but the number seems too high). This makes it seem like there is some issue with primarily Xiaomi devices and install time bundles, sometimes behaving as fastfollow bundles instead of install time bundles. 

We've also got more confirmation that some users are having issues while installing through Google play.

Any thoughts @jamcohen ?

**Comment by jamcohen** [comment]
Hi Jurjen,

Thanks for investigating this and bringing it to our attention. I'm reaching out to folks internally to get more info and I'll get back to you as I learn more.

Do you know if any of the affected users are using Android 10 or above? Those versions of Android should prevent apks from being installed without their install-time packs.

**Comment by JurjenBiewenga** [comment]
Hey @jamcohen,

I've attached some aggregated data of the android versions and devices used by users that have had this issue since we've released the update including install time assets.

![Screenshot 2021-04-29 at 10 45 06](https://user-images.githubusercontent.com/3128681/116525706-780a9700-a8e1-11eb-9de0-dd4ea7a29109.png)
![Screenshot 2021-04-29 at 10 45 15](https://user-images.githubusercontent.com/3128681/116525712-793bc400-a8e1-11eb-9875-35c27d85df46.png)
![Screenshot 2021-04-29 at 10 45 22](https://user-images.githubusercontent.com/3128681/116525716-79d45a80-a8e1-11eb-88c9-ba28f05be3af.png)

**Comment by jamcohen** [comment]
Hi @JurjenBiewenga,

Thanks for those stats.

The Play Store and Android 10 both have checks that prevent base apks from being installed without the necessary install-time packs. It seems like on Xiaomi devices those checks are being circumvented.

I did come across an internal bug where disabling `miui optimizations` caused apps to be installed without install-time packs. Could you check if the affected users had `miui optimizations` disabled when they installed the app?

**Comment by JurjenBiewenga** [comment]
Thanks @jamcohen, I'll try to investigate that. I'm fairly sure that we don't have that data currently available but I'll ask our support to verify whether `miui optimizations` is disabled.

**Comment by jamcohen** [comment]
Thanks @JurjenBiewenga,

We can also try to reproduce the issue on our end.
Do you mind sharing the package name and version number of your app (If you prefer you can also email us at play-unity-plugin-support@googlegroups.com).

**Comment by JurjenBiewenga** [comment]
To give a bit of context in case someone else runs into the same issue.

We've spent a few weeks trying to figure out where the issues where coming from however nothing conclusive was found, our issues slowly started disappearing after releasing patches to our game. This seems to point to some weird bug that only happens when install time assets are introduced and somehow gets resolved after the user downloads patches/updates.
