### ISSUE TITLE
example code to build app bundle in batchmode

### ISSUE THREAD

**Issue by joonjoonjoon** [google/play-unity-plugins#105]
Is there any example code on how to build an App Bundle in batchmode?

The `AppBundlePublisher.CreateAppBundleBuilder` function is private for example, how are we supposed to get this object?

**Comment by thanwah** [comment]
One example of building an app bundle in batchmode is from the [AssetDeliveryDemo](https://github.com/google/play-unity-plugins/blob/95e360ec4bbde268a02fe24951d01b1fb9312eaf/GooglePlayPlugins/com.google.play.assetdelivery/Samples/AssetDeliveryDemo/Editor/Scripts/DemoBuilder.cs#L94).

Classes in the "Internal" directories aren't considered public API, whereas the [Bundletool](https://github.com/google/play-unity-plugins/blob/master/GooglePlayPlugins/com.google.android.appbundle/Editor/Scripts/Bundletool.cs) class is public API.

**Comment by joonjoonjoon** [comment]
if I have already built the asset bundles, what's the correct way to build the `assetPackConfig` objec that I need to pass to `Bundletool.BuildBundle`?

**Comment by thanwah** [comment]
Sorry, I should've mentioned that this is documented at https://developer.android.com/guide/playcore/asset-delivery/integrate-unity#configure-asset-packs-api.

Please let me know if anything is unclear.

**Comment by joonjoonjoon** [comment]
thank you, that is what I needed.

is there a resource/example about how to re-build the asset packs from code?
I am using the Build command of the AssetBundle Browser window, but would like to automate the process.
In the demo script you linked, it seems like they are defining the entire assetbundle from scratch, with hardcoded GUID's which feels not scalable.

**Comment by joonjoonjoon** [comment]
I'm learning more about assetbundles and I understand that this question is likely out of scope for this plugin.
Documentation on how to create assetbundles are available in the Unity documentation and are not specific to Google Play plugins. I'll close the issue, thanks for the help.
