### ISSUE TITLE
App Bundle package errors if Unity Android not installed

### ISSUE THREAD

**Issue by jsteinich** [google/play-unity-plugins#11]
Our game supports both Android and iOS. We build the two platforms using separate servers with each having their respective unity platform components.
I'm in the process of switching the Android side from just Unity IAP to Unity IAP + Google Play Billing. In doing so, the Android app bundle package is installed as a dependency.
Now when building for iOS, the app bundle package fails to compile with the following errors:
<code>
Library/PackageCache/com.google.android.appbundle@1.0.0/Editor/Scripts/Internal/BuildTools/JavaUtils.cs(107,32): error CS0234: The type or namespace name 'AndroidExternalToolsSettings' does not exist in the namespace 'UnityEditor.Android' (are you missing an assembly reference?)
Library/PackageCache/com.google.android.appbundle@1.0.0/Editor/Scripts/Internal/BuildTools/AndroidSdk.cs(41,27): error CS0234: The type or namespace name 'AndroidExternalToolsSettings' does not exist in the namespace 'UnityEditor.Android' (are you missing an assembly reference?)
Library/PackageCache/com.google.android.appbundle@1.0.0/Editor/Scripts/Internal/BuildTools/AndroidSdk.cs(85,23): error CS0234: The type or namespace name 'AndroidExternalToolsSettings' does not exist in the namespace 'UnityEditor.Android' (are you missing an assembly reference?)
Library/PackageCache/com.google.android.appbundle@1.0.0/Editor/Scripts/Internal/BuildTools/AndroidSdk.cs(86,24): error CS0234: The type or namespace name 'AndroidExternalToolsSettings' does not exist in the namespace 'UnityEditor.Android' (are you missing an assembly reference?)
Library/PackageCache/com.google.android.appbundle@1.0.0/Editor/Scripts/Internal/BuildTools/AndroidSdk.cs(88,23): error CS0234: The type or namespace name 'AndroidExternalToolsSettings' does not exist in the namespace 'UnityEditor.Android' (are you missing an assembly reference?)
Library/PackageCache/com.google.android.appbundle@1.0.0/Editor/Scripts/Internal/BuildTools/AndroidSdk.cs(89,24): error CS0234: The type or namespace name 'AndroidExternalToolsSettings' does not exist in the namespace 'UnityEditor.Android' (are you missing an assembly reference?)
</code>

I'm not aware of anyway to make package references only apply with certain targets and adding the Android components would cause build slowdowns.

I could put together a quick PR adding some `#if UNITY_ANDROID` blocks, but perhaps there is a better way.

**Comment by jamcohen** [comment]
Thanks for bringing this up. There should be no need for `#if` blocks, since we have [.asmdef](https://github.com/google/play-unity-plugins/blob/master/GooglePlayPlugins/com.google.android.appbundle/Editor/Google.Android.AppBundle.Editor.asmdef) files that should prevent packages from being included in iOS builds.

Which Unity version are you using?
In your `com.google.android.appbundle` folder, do you see a `Google.Android.AppBundle.Editor.asmdef` file? If you select it in Unity you should see this in your inspector: 
<img width="511" alt="Screen Shot 2020-04-30 at 1 39 17 PM" src="https://user-images.githubusercontent.com/4805315/80756833-0f2eea00-8ae8-11ea-84cc-ea28277b8919.png">

Thanks again, hopefully we can get this resolved for you.

**Comment by jamcohen** [comment]
I tested on 2019.3.5f1 and couldn't reproduce the issue.
Does the issue occur when building locally (i.e. not on your build server)?
Also, just to clarify, you do not run into this when you build for Android, correct?

**Comment by jsteinich** [comment]
I don't actually have that folder since I am referencing it as a package (technically it is in  Library/PackageCache).
I just have `"com.google.play.billing": "2.2.0"` in my `Packages/manifest.json` file as a result of following https://developer.android.com/google/play/billing/unity

I'm on Unity 2019.3.0f6. I don't have the issue locally, but I also have the Unity Android component installed. An Android build is successful.

The asmdef file is just saying to only include in editor, which is correct; however, I believe some Android (and iOS) editor components only exist if the associated Unity component is installed.
I ran into something similar a couple weeks ago when referencing something from `UnityEditor.Android` namespace.

**Comment by jamcohen** [comment]
Ah I see, I'll try installing 2019.3.0f6 without the Android component and see if I run into the same issue.

**Comment by jamcohen** [comment]
I was able to reproduce the issue and submitted a fix to our internal repo.
Once that's reviewed and finalized we'll push the fix to Github.
Thanks again for bringing this to our attention!

**Comment by jamcohen** [comment]
Just pushed [the fix to github](https://github.com/google/play-unity-plugins/commit/481e45ebddba897d588b4a3862b789a8431f0b70).
Once we cut a new release it will be available from the Unity package manager.

**Comment by jamcohen** [comment]
Release [v1.1.0](https://github.com/google/play-unity-plugins/releases/tag/v1.1.0) includes this fix. Feel free to reopen if the issue persists.

**Comment by dginovker** [comment]
Getting same issue with v1.5.0, anyone else?
