### ISSUE TITLE
Cannot load VideoClip from asset bundles on Android

### ISSUE THREAD

**Issue by davidejones88** [google/play-unity-plugins#117]
Is loading VideoClips from asset bundles supported for Android? I was able to run the plugin entire flow (bundle, create, deploy aab, load inside the game, etc) for a Sprite object, but when I tried with a VideoClip object

`Object[] objects = assetBundle.LoadAllAssets();`

is empty. I have already double-checked the names and everything seems to be working fine.

**Comment by davidejones88** [comment]
Sorry, this has nothing to do with the plugin. The problem was that Unity was stripping out the VideoClip class as it was not direclty used in the Scenes but only in bundles. For reference, here's a proper way to solve this: https://forum.unity.com/threads/videoclip-in-assetbundle-on-ios.988364/

**Comment by ShaubertIlya** [comment]
Hi there. @davidejones88 could you please specify how exactly you did manage the assetbundles work on iOS?

I have the same issue. I've tried to specify bundle as VideoClip in my code, turned off caching compression, turned off compression when creating assetbundles for iOS. But there is no result. Works fine in the editor though.

I’m trying to get files from my hosting server, phase.kz/AssetBundles/charyn_video-IOS. Just mp4 file.

**Comment by davidejones88** [comment]
@ShaubertIlya Hello!
The problem I faced was caused by the fact that I had zero references in the code to the VideoClip class, so Unity stripped it out during deployment. I have added the Video classes to the link.xml file as specified here: https://forum.unity.com/threads/videoclip-in-assetbundle-on-ios.988364/ and things started to work automatically. Let me know if you tried this already. 

Based on my knowledge there is no need for special compression or anything like that to prepare VideoClips in AssetsBundles for Unity.

**Comment by ShaubertIlya** [comment]
@davidejones88 yeah, I’ve found that post as well, but I don’t get what’s the link.xml file

**Comment by davidejones88** [comment]
@ShaubertIlya Here you can find the full documentation of code stripping in Unity: https://docs.unity3d.com/Manual/ManagedCodeStripping.html In particular the "Link XML" section. 

Basically, just create a file named link.xml, drop it into your Assets folder in Unity. In the xml file add these lines

```
<linker>
  <assembly fullname="UnityEngine.Video" preserve="all"/>
  <assembly fullname="UnityEngine.VideoModule" preserve ="all"/>
</linker>
```

and you should be good to go! Let me know if this works

**Comment by ShaubertIlya** [comment]
@davidejones88 thanks a lot! That helped. You're guys rock!
