### ISSUE TITLE
aab is load very slow than apk

### ISSUE THREAD

**Issue by tongbenchuan** [google/play-unity-plugins#118]
it is slowly to use PlayAssetDelivery.RetrieveAssetPackAsync().LoadAssetBundleAsync than use AssetBundle.LoadFromFileAsync
how can i improve this problem

**Comment by jamcohen** [comment]
If you're loading the AssetBundle more than once, you can cache the `AssetLocation` returned from `PlayAssetPackRequest.GetAssetLocation("assetBundleName")` and use that for subsequent calls (`AssetBundle.LoadFromFileAsync(assetLocation.Path, /* crc= */ 0, assetLocation.Offset);`). 

LoadAssetBundleAsync calls a method in the underlying Java library which has some performance overhead, which the above method avoids.
