### ISSUE TITLE
NullReferenceException at Google.Play.AssetDelivery after Removing AssetPacks

### ISSUE THREAD

**Issue by GiovanniMeloni** [google/play-unity-plugins#120]
Hello! This may be a similar problem from issue #112 but I'm not sure if its the same.

I've implemented a "Remove Products" button in my game that basically calls the` RemoveAssetPack()` for each assetPack. When testing trough the` Google -> Build` and Run it works fine.
But when I upload to Internal Testing I keep getting the NullReference error when trying to download the assets again:

1. Open the app
2. Download the AssetPacks.
3. Click "Remove" button (Calls `RemoveAssetPack()`)
4. Close the app
5. Reopen the app
6. Try to download an asset but error is thrown.

```
06-24 17:49:18.932 15189 15233 E Unity : NullReferenceException: Object reference not set to an instance of an object.
06-24 17:49:18.932 15189 15233 E Unity : at AssetPackAsyncLoader+d__0.MoveNext () [0x00000] in <00000000000000000000000000000000>:0
06-24 17:49:18.932 15189 15233 E Unity : at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0
```

I've been trying to understand where exactly it fails, and I've discovered that It works just fine until I call the PlayAssetPackRequest.LoadAssetBundleAsync() method, it returns null as it can be seen in these logs:

```
06-24 17:49:18.853 15189 15233 I Unity : Calling get asset location, assetPackName: harvester9250_android, path: assetpack/harvester9250_android
06-24 17:49:18.853 15189 15233 I Unity : UnityEngine.Logger:LogFormat(LogType, String, Object[])
06-24 17:49:18.853 15189 15233 I Unity : UnityEngine.Debug:LogFormat(String, Object[])
06-24 17:49:18.853 15189 15233 I Unity : Google.Play.AssetDelivery.Internal.AssetPackManager:GetAssetLocation(String, String)
06-24 17:49:18.853 15189 15233 I Unity : Google.Play.AssetDelivery.Internal.PlayAssetPackRequestImpl:LoadAssetBundleAsync(String)
06-24 17:49:18.853 15189 15233 I Unity : d__0:MoveNext()
06-24 17:49:18.853 15189 15233 I Unity : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
06-24 17:49:18.853 15189 15233 I Unity :
06-24 17:49:18.891 15189 15189 D ViewRootImpl@9c13879[UnityPlayerActivity]: ViewPostIme pointer 0
06-24 17:49:18.929 15189 15233 E Unity : [MANUAL-LOG][AsyncLoader Script][harvester9250_android] AFTER BUNDLE REQUEST: Content of bundleRequest:
06-24 17:49:18.929 15189 15233 E Unity : UnityEngine.Logger:Log(LogType, Object)
06-24 17:49:18.929 15189 15233 E Unity : d__0:MoveNext()
06-24 17:49:18.929 15189 15233 E Unity : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
06-24 17:49:18.929 15189 15233 I Unity :
06-24 17:49:18.932 15189 15233 E Unity : NullReferenceException: Object reference not set to an instance of an object.
06-24 17:49:18.932 15189 15233 E Unity : at AssetPackAsyncLoader+d__0.MoveNext () [0x00000] in <00000000000000000000000000000000>:0
06-24 17:49:18.932 15189 15233 E Unity : at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0
```

After the "Content of BundleRequest:" it should show the Request, but shows nothing. Here's a log example of what it should be showing:

`06-24 17:36:10.286 13860 13895 E Unity : [MANUAL-LOG][AsyncLoader Script][harvester9250_android] AFTER BUNDLE REQUEST: Content of bundleRequest: UnityEngine.AssetBundleCreateRequest`

Any help would be appreciated. If there's need for more information Id be happy to give.

**Comment by jamcohen** [comment]
Hi Giovanni,

This looks like a separate issue, but it could be related.

What version of Unity are you using?

Before you call `PlayAssetPackRequest.LoadAssetBundleAsync()` is the `PlayAssetPackRequest.Error` set to `NoError`?

**Comment by GiovanniMeloni** [comment]
Good to hear back!
Currently my project is using Unity Version 2020.3.9f1.

I am indeed checking the `PlayAssetPackRequest.Error` variable before calling `PlayAssetPackRequest.LoadAssetBundleAsync()`. Here's the snippet:

```
//--------------------------------------
        PlayAssetPackRequest assetPackRequest = PlayAssetDelivery.RetrieveAssetPackAsync(bundleName);
        yield return assetPackRequest;

        Debug.Log($"[MANUAL-LOG][AsyncLoader Script][{bundleName}] AssetPackRequest complete");
        if(assetPackRequest.Error != AssetDeliveryErrorCode.NoError)
        {
            Debug.LogError($"[MANUAL-LOG][AsyncLoader Script][{bundleName}] Error occured retrieving assetPackRequest: {assetPackRequest.Error}");
            yield break;
        }


        AssetBundleCreateRequest bundleRequest = assetPackRequest.LoadAssetBundleAsync(bundleName);
        yield return bundleRequest;

        Debug.LogError($"[MANUAL-LOG][AsyncLoader Script][{bundleName}] AFTER BUNDLE REQUEST: Content of bundleRequest: {bundleRequest}");
//--------------------------------------
```

The conditional is never called which means it is set to `NoError`. I've also checked the `PlayAssetPackRequest.Status` content and it comes back as 'Available'.

**Comment by jamcohen** [comment]
Hmm, that is strange.
Could you try running `adb shell` and navigating to this folder:
`/data/data/<com.your.apps.package.name>/files/assetpacks`

That folder will contain all of your downloaded on-demand assetpacks.
Could you check if the asset pack you're looking for exists in that folder?

Could you also try restarting your device instead of closing and reopening the app, and seeing if the error persists?

Thank you!

**Comment by jamcohen** [comment]
@GiovanniMeloni, now that issue #112 is fixed, it might be worth checking if your still experiencing this issue with the latest version of the Play Store.

**Comment by GiovanniMeloni** [comment]
> @GiovanniMeloni, now that issue #112 is fixed, it might be worth updating the Play Store on your device and checking if your issue still occurs.

Hi! Sorry for taking a while to reply. After your message, 2 days ago, I was going to proceed as suggested with `adb shell`, but decided to restart my device, just because.
After the restart, this issue with removing assets got resolved and it got me really confused, especially because we were also having the same issue as #112, but that also started to work, hence why it took a while to get back to you. 
I now see that the latest update was June 28th, I'm guessing this fix was included in that update which would explain why it started to work out of a sudden lol. Thanks for the fix!!

**Comment by jamcohen** [comment]
lol, no worries at all!
I'm glad it's all resolved.
