### ISSUE TITLE
When is an asset pack considered large?

### ISSUE THREAD

**Issue by happypepper** [google/play-unity-plugins#121]
Hi Google,

From this page: https://developer.android.com/reference/unity/class/Google/Play/AssetDelivery/PlayAssetDelivery#classGoogle_1_1Play_1_1AssetDelivery_1_1PlayAssetDelivery_1a645c63f6c09754d963b166f8072dc567

"A PlayAssetBundleRequest is set to AssetDeliveryStatus.WaitingForWifi if the user is currently not on a Wi-Fi connection and the AssetBundle is large"
But I couldn't find any number about what makes an AssetBundle "large". Does anyone know this threshold?

**Comment by CellFari** [comment]
I50 mb is the limit
Large downloads
Asset packs larger than 150MB can download automatically, but only on Wi-Fi. If the user is not on Wi-Fi, the PlayAssetBundleRequest status is set to AssetDeliveryStatus.WaitingForWifi and the download is paused. In this case, either wait until the device connects to Wi-Fi, resuming the download, or prompt the user for approval to download the pack over a cellular connection.

![image](https://user-images.githubusercontent.com/45685937/123945368-8182af00-d9b7-11eb-99e3-c39b2d0e54c1.png)

**Comment by happypepper** [comment]
Ah.. missed that diagram. thanks alot
