### ISSUE TITLE
Signing failed: Failed to locate keystore file: user.keystore

### ISSUE THREAD

**Issue by L4Hacks** [google/play-unity-plugins#122]
Unity 2020.2.5f1.
Everything is working.
I can compile tha pp bundle from the Unity Build properties panel, but when i use the "Google" tab to build the app, i get an error complaining about the keystore file, which i already set multiple times in the Players Settings.

My questions are:
- is there any diference between using the Unity Build panel and using Google > build ?
- if there is, how do i fix this problem.

Best regards,
José

**Comment by L4Hacks** [comment]
found out the problem is that the Keystore should be inside the project folder.

**Comment by oliveirachristian151-cyber** [comment]
Deu certo para você aqui aparece esse erro.

Signing failed: Failed to locate keystore file: Documents/user.keystore
