### ISSUE TITLE
Building Android Player with LZ4

### ISSUE THREAD

**Issue by LukaszHynek** [google/play-unity-plugins#131]
Building the AAB with the plugin builds the Android Player without any compression, build options are set in here:
![image](https://user-images.githubusercontent.com/71314134/127004117-38d7cb29-a312-4124-9868-a9e0f7e808b5.png)

The result is a lot bigger assets in base_assets (we are using the split option as our games are much larger than 150MB)
In some cases the app is x2-x3 times larger when installed which is unaceptable when normally the game is already on the heavier side.
I have built AABs through the regular Unity build window to see how they differ and that is how i got to see that **assets/bin/data** contains quite different results:
![image](https://user-images.githubusercontent.com/71314134/127005407-8624cbe0-e73d-4403-b23f-9446b25549e4.png)

The only difference in the building process is one missing build option **CompressWithLz4** 
So i tried to add it to the configuration:
![image](https://user-images.githubusercontent.com/71314134/127005705-ce5a82e7-7b02-46eb-91e6-d3d7d5b4dbe9.png)

After building I saw exactly what i wanted:
![image](https://user-images.githubusercontent.com/71314134/127005853-a76b4a5e-8aaa-47c3-b1d5-ac9a3cffec2d.png)

Split assets and compressed just like a normal Unity build, but unfortunately after hitting Build And Run this is what i get:
![image](https://user-images.githubusercontent.com/71314134/127005999-7ee58e3b-b77b-498a-aa50-390c2a942681.png)

With the log saying:
![image](https://user-images.githubusercontent.com/71314134/127007235-18f76f30-4f0a-4ed2-87eb-91940cca4924.png)

Only thing i was able to Google out of this is that it means the build was not complete / is broken.

This is the only real obstacle we are facing from completely moving to .AAB.
Any solutions to reenabling build compression while maintaining base module split are greatly appreciated.

Aditionally I have tried to build an APK using bundletool manually through the command line and was able to build a working one using the **--mode=universal** parameter forcing the build of a all-in-one APK - that one worked meaning that the bundle does contain everything needed but just doesn't put it together properly when building APKs normally

**Comment by jamcohen** [comment]
Hi @LukaszHynek,

Thanks for the detailed post.
I was able to reproduce the issue on 2020.3.14f1.
I'm not sure why Unity has trouble loading the assets from the data.unity3d in this case, but I'll investigate.

As far as compression goes, are you compressing to reduce install size or download size?

 If it's download size, compression might not help as much as you'd expect because app bundles are compressed when they're delivered to the user. You can look at the [App Bundle Explorer](https://play.google.com/console/about/app-bundle-explorer/) to determine the download size of the asset packs within your app.

If you're concerned about the amount of space the app takes up on the users device, you could try building with [CompressInstallTimeAssetPacks](https://github.com/google/play-unity-plugins/blob/e6134882f68c7d04b322d82dbe778545dfefab12/GooglePlayPlugins/com.google.android.appbundle/Editor/Scripts/CompressionOptions.cs#L42) set to `true`. That will ensure that the contents of base.apk and base_asset.apk will be compressed.

**Comment by Sarrac3873** [comment]
> Building the AAB with the plugin builds the Android Player without any compression, build options are set in here:
> ![image](https://user-images.githubusercontent.com/71314134/127004117-38d7cb29-a312-4124-9868-a9e0f7e808b5.png)
> 
> The result is a lot bigger assets in base_assets (we are using the split option as our games are much larger than 150MB)
> In some cases the app is x2-x3 times larger when installed which is unaceptable when normally the game is already on the heavier side.
> I have built AABs through the regular Unity build window to see how they differ and that is how i got to see that **assets/bin/data** contains quite different results:
> ![image](https://user-images.githubusercontent.com/71314134/127005407-8624cbe0-e73d-4403-b23f-9446b25549e4.png)
> 
> The only difference in the building process is one missing build option **CompressWithLz4**
> So i tried to add it to the configuration:
> ![image](https://user-images.githubusercontent.com/71314134/127005705-ce5a82e7-7b02-46eb-91e6-d3d7d5b4dbe9.png)
> 
> After building I saw exactly what i wanted:
> ![image](https://user-images.githubusercontent.com/71314134/127005853-a76b4a5e-8aaa-47c3-b1d5-ac9a3cffec2d.png)
> 
> Split assets and compressed just like a normal Unity build, but unfortunately after hitting Build And Run this is what i get:
> ![image](https://user-images.githubusercontent.com/71314134/127005999-7ee58e3b-b77b-498a-aa50-390c2a942681.png)
> 
> With the log saying:
> ![image](https://user-images.githubusercontent.com/71314134/127007235-18f76f30-4f0a-4ed2-87eb-91940cca4924.png)
> 
> Only thing i was able to Google out of this is that it means the build was not complete / is broken.
> 
> This is the only real obstacle we are facing from completely moving to .AAB.
> Any solutions to reenabling build compression while maintaining base module split are greatly appreciated.
> 
> Aditionally I have tried to build an APK using bundletool manually through the command line and was able to build a working one using the **--mode=universal** parameter forcing the build of a all-in-one APK - that one worked meaning that the bundle does contain everything needed but just doesn't put it together properly when building APKs normally

**Comment by LukaszHynek** [comment]
Hi @jamcohen,

Thanks for looking into the problem.
We were mainly concerned with the install size on user devices, our games can take about 300-400 MB so increasing the size by x2 or more was a big problem.

I am happy to report that the CompressInstallTimeAssetPacks option works and the results speak for themselves:
APK, currently on store - 154 MB
AAB built with the plugin out of the box - 351 MB
AAB built today with the compress option - 149 MB

We have even saved some space as AAB are supposed to 😄
I have even tried this variable before but setting it did not seem to change anything in the AAB so i thought is is unused or not working as there is no mention of it in any docs (by the way there is no mention of the base module split either).
Turns out it works but when installed on the device - makes sens now because the AAB is already compressed so it applies to teh generated APK and not the AAB size.
Any mention of this in the docs could probably save people some time.

Now my question is - Why is that not the default ?
It seems that every project built with the default configuration will not have any compression on assets and that can make the games a lot bigger instead of smaller.
The download size is small but is there any reason to not enable install-time asset pack compression by default ?
Maybe as an aditional checkbox ?

I will be adding this to our internal version of the plugin together with a target location choice when doing Build and Run as that is the deafult behaviour when building with Unity as it allows to test and upload the AAB when the test is done without having to run Build AAB again just to get the file without digging in temporary folders/files.

**Comment by jamcohen** [comment]
I'm glad `CompressInstallTimeAssetPacks` worked for you!

> Now my question is - Why is that not the default ?

That's a good question. We default to uncompressed in order to optimize download size and loading speed. When apks are served to the device they're additionally compressed "over-the-wire". That compression is more effective on data that hasn't already been compressed. This means that setting `CompressInstallTimeAssetPacks` to true can counterintuitively increase the download size. Once the apk is installed, loading assets can be slower because the assets need to be uncompressed on the fly.

We didn't expose that option as a checkbox because we assumed, maybe incorrectly, that most developers would optimize download size/loading speed over disk size. We'll consider exposing these options in build settings.

Thanks for the suggestions for Build and Run as well!

**Comment by D33pTh0ught** [comment]
Hi @jamcohen
is `CompressInstallTimeAssetPacks` set to true per default in version 1.6?
If not, how would i set this? I'm not quite sure where I should set this value.

**Comment by LukaszHynek** [comment]
Hi @D33pTh0ught,
I don't know if you are still looking for this but having dealt with this issue myself I know it takes a bit of looking around.
If it is not enabled by default in the current version (I am using an older version that I customized for my use case) - you have to manually set this option.
From what I can tell by having a quick look ok GitHub i would say that you can change the settings around here:
https://github.com/google/play-unity-plugins/blob/ef290c7634e219c193dc0eeccdd2bf416951f201/GooglePlayPlugins/com.google.android.appbundle/Editor/Scripts/Internal/BuildTools/AppBundleBuilder.cs#L281
This is the place where CreateBundleOptions are created and inside them you can see the CompressionOptions.
Now you only need to set the CompressInstallTimeAssetPacks to true like so:
![image](https://user-images.githubusercontent.com/71314134/147458112-d1ecf70d-e509-4cd0-8048-1676a190f255.png)
But make sure you do it before it has a chance to use the old options - do it right after line 286.

Also, if you are using the Unity Addressable Asset System then you should also add this:
![image](https://user-images.githubusercontent.com/71314134/147458510-75f2e84c-28b9-44a8-a6f0-d08b5577e9ed.png)
This fixes an issue with **very** long loading times when using that system - as it is something to do with compression I suspect it compresses these assets but they are already compressed and Unity really doesn't like that.

Keep in mind that i have a bit of an older version, you might have to look into how it works now when adding these UncompressedGlobs changes as i have no idea if they exist already by that point so the first line might be useless or might even break something if there is already something there since this effectively gets rid of everything and only adds this addressables path.

**Comment by D33pTh0ught** [comment]
Thanks for the response and the hints @LukaszHynek 
After testing your suggestions I would guess that this option is now enabled by default, since there is no change in the size of the build.
