### ISSUE TITLE
Failed to retrieve asset pack: Asset Pack Download Error(-1): The requesting app is unavailable (e.g. unpublished, nonexistent version code). (https://developer.android.com/reference/com/google/android/play/core/assetpacks/model/AssetPackErrorCode.html#APP_UNAVAILABLE)

### ISSUE THREAD

**Issue by vbashiri** [google/play-unity-plugins#132]
Hi there,
I get this error when try to get asset packs.
```
2021/07/27 07:45:06.357 15696 18367 Error Unity Failed to retrieve asset pack: Asset Pack Download Error(-1): The requesting app is unavailable (e.g. unpublished, nonexistent version code). (https://developer.android.com/reference/com/google/android/play/core/assetpacks/model/AssetPackErrorCode.html#APP_UNAVAILABLE)
2021/07/27 07:45:06.357 15696 18367 Error Unity UnityEngine.Logger:LogFormat(LogType, String, Object[])
2021/07/27 07:45:06.357 15696 18367 Error Unity UnityEngine.Debug:LogErrorFormat(String, Object[])
2021/07/27 07:45:06.357 15696 18367 Error Unity Google.Play.AssetDelivery.Internal.<>c__DisplayClass15_1:<InitiateRequest>b__1(String, Int32)
2021/07/27 07:45:06.357 15696 18367 Error Unity System.Action`2:Invoke(T1, T2)
2021/07/27 07:45:06.357 15696 18367 Error Unity System.Action:Invoke()
2021/07/27 07:45:06.357 15696 18367 Error Unity Google.Play.Core.Internal.PlayCoreEventHandler:Update()
```

More info:
I ran to this error when I tried to get asset packs using `PlayAssetDelivery.RetrieveAssetBundleAsync(assetBundleName)`.
I checked asset packs in Google > Android App Bundle > Asset Delivery Settings and Assets Delivery mode are OnDemand and it shows no error. (The dependency field is left empty). Then run the app with Google > Build Android App Bundle (It is Instant app
so I already have Instant package as suggested here: https://github.com/google/play-unity-plugins/issues/6#issuecomment-616909987).

Also I tried to get asset packs with unity api with absolute address and it works on editor. (so I assume asset bundles are fine). I tried to check the asset bundles files with ./adb shell as you suggested here: https://github.com/google/play-unity-plugins/issues/120#issuecomment-869915466
The folder assetPacks doesn't exist.

```
a50:/data/data/com.funtory.roborace/files $ cd assetPacks
/system/bin/sh: cd: /data/data/com.funtory.roborace/files/assetPacks: No such fi
le or directory
```
but the folders with asset bundles' names exist in built .aab file.

To add more, `bundleRequest.Error` shows NoError and `bundleRequest.Status` go from Pending to the mentioned error.

**Comment by vbashiri** [comment]
Installing app from google play internal test fixed this issue. The error for standard build was different from Instant build. The error in standard build is as follows which is also fixed by this approach.

```
2021/07/27 14:04:56.971 13268 16545 Error Unity Failed to retrieve asset pack: Asset Pack Download Error(-13): The app is not owned by any user on this device. An app is "owned" if it has been acquired from Play. (https://developer.android.com/reference/com/google/android/play/core/assetpacks/model/AssetPackErrorCode.html#APP_NOT_OWNED)
2021/07/27 14:04:56.971 13268 16545 Error Unity Google.Play.AssetDelivery.Internal.<>c__DisplayClass15_1:<InitiateRequest>b__1(String, Int32)
2021/07/27 14:04:56.971 13268 16545 Error Unity System.Action`2:Invoke(T1, T2)
2021/07/27 14:04:56.971 13268 16545 Error Unity System.Action:Invoke()
2021/07/27 14:04:56.971 13268 16545 Error Unity Google.Play.Core.Internal.PlayCoreEventHandler:Update()
2021/07/27 14:04:56.971 13268 16545 Error Unity  
2021/07/27 14:04:56.971 13268 16545 Error Unity (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 39)
2021/07/27 14:04:56.971 13268 16545 Error Unity 

```

**Comment by Fourteen-mi** [comment]
Did you fixed it?   I have been running to the same issue.Intalling app form google play or useing Bundle tools with order "--local -testing".Gussing that the review team not correctly intall the app.

**Comment by vbashiri** [comment]
@Fourteen-mi Well I did so many thing I don't exactly know what did the trick. here are some tips:

First of all, - - local-testimg will work if you install the instant aab file on your device as a normal app (yes, you can do it. just make sure the instant version was not installed on ur device and install extracted apks) here is a gist I made to automate the process: https://gist.github.com/vbashiri/d0faf07421d98b2f40632022270e3f62

Second, Internal test should work, but not always. In some cases I've got the same error even installing from google play. to solve that:
Use google asset delivery 1.7.0 with highest android core possible. I don't access the project right now to check the exact version.
