### ISSUE TITLE
Play Asset Delivery - Download/Load Decouple

### ISSUE THREAD

**Issue by asrakan** [google/play-unity-plugins#17]
Hello we recently started to using Play Asset Delivery for our multiplayer fps game(https://play.google.com/store/apps/details?id=com.critical.strike2).  But there are some problems we are  having one of them is the download and load logic in the same function which is hard to control since sometimes you don't need to load instantly the data but after the some time. Can we somehow split the download function and load function.

**Comment by thanwah** [comment]
Thanks for sharing this feedback! We're working on a new API that should allow for downloading separately from AssetBundle loading. We might also want to think about making this optional on the original API.

FYI @jamcohen

**Comment by asrakan** [comment]
Thank you for the answers, when will the new API will be released?

**Comment by jamcohen** [comment]
We just released this as part of the v1.1.1 release as an experimental feature. If you want to give it a try, you can enable the PLAY_ASSET_DELIVERY_EXPERIMENTAL preprocessor definition in player settings (see the "Platform custom #defines" section [here](https://docs.unity3d.com/Manual/PlatformDependentCompilation.html) for how to do that)

**Comment by lzqlawrence** [comment]
@thanwah Do you means that I can use synchronous methods to load the assets while finishing the download process?
@jamcohen Just `RetrieveAssetPackAsync` and `RetrieveAssetPackBatchAsync` were found, could you please show me the new API?

**Comment by binouze** [comment]
Really nice thanks.
Would be nice to have an helper method on PlayAssetPackBatchRequest to see the overall DownloadProgress without manually looping the Requests.

**Comment by jamcohen** [comment]
@lzqlawrence Apologies for missing your comment. We have since removed the experimental tags (in v1.2) and addd public documentation. The separate load methods are in the AssetPackRequest object (see [here](https://developer.android.com/guide/playcore/asset-delivery/integrate-unity?language=api#asset-type)).
@binouze Thank you for the suggestion, I'll add this as a TODO.
