### ISSUE TITLE
Is Play Integrity plugin available?

### ISSUE THREAD

**Issue by kuoliangkwong** [google/play-unity-plugins#174]
Is the library available? I can't find that `.unitypackage` in Releases. Also tried importing all other `.unitypackage`, but they do not have any SDK API related to that. However, I can find the documentation here [https://developer.android.com/google/play/integrity/verdict#unity](url)

**Comment by Arivval** [comment]
Update: The Play Integrity API Unity plugin is available now with the release of [v1.7.0](https://github.com/google/play-unity-plugins/releases/tag/v1.7.0).

**Comment by Kumici13** [comment]
Is there some implementation guide, or I only need to import it?

**Comment by mcolombo** [comment]
Where can I find some C# implementation of these?
There's only android
