### ISSUE TITLE
Confusing Integrity implementation

### ISSUE THREAD

**Issue by nvdg** [google/play-unity-plugins#177]
I have some trouble with the new Integrity plugin. And it seems that it's only been implemented partly or I don't understand how it works. I have some trouble with modded versions of my game and to my understanding, the Integrity SDK should be able to tell me if the game is the original game downloaded from the Play Store or a modded version from elsewhere.

How I hoped the SDK would work is I just call a function that connects with Google Play and returns the integrity information.
Unfortunately, it's not that straightforward...
The documentation (https://developer.android.com/google/play/integrity/verdict#unity) only contains an example for Unity to receive the encrypted token, but I have no idea what to do with this token now from inside Unity...
The documentation advises decrypting it on the Google Play servers but there are no functions for this inside the current SDK and also no documentation on how to do this from Unity.

I simple async operation 'IntegrityManager.CheckIntegrity()' that just returns the serialized payload as a c# class and handles all the steps in between would be great. Or at least continue the implementation and documentation on what to do with the encrypted token in Unity.

**Comment by Arivval** [comment]
Hi @nvdg,

Thank you for reaching out. It is strongly discouraged to decrypt and verify and integrity token response on client side given the assumption that client side implementation can be maliciously altered and can't be trusted. After fetching the token in your Unity built game, you can send it to your server and complete the server-side integrity verdict as mentioned here: https://developer.android.com/google/play/integrity/verdict#decrypt-verify

Best,
John

**Comment by Arivval** [comment]
Hi @nvdg 

Google's server here is referring to the server in the [Google Cloud project linked to your app](https://developer.android.com/google/play/integrity/setup#enable-responses).

Note, regardless whether the token is decrypted & verified in [Google's server's](https://developer.android.com/google/play/integrity/verdict#decrypt-verify-google-servers) or in [your own secure server environment](https://developer.android.com/google/play/integrity/verdict#decrypt-verify-locally), you still need to fetch/have the decoded token response available in your app's backend and make decisions in backend's control flow accordingly (e.g. disable authentication, IAP, or multiplayer feature if the response is not legitimate).
