### ISSUE TITLE
FileNotFoundException: Asset pack directory doesn't exist Google.Android.AppBundle.Editor.AssetPackConfig.AddAssetsFolder 

### ISSUE THREAD

**Issue by auXtern** [google/play-unity-plugins#179]
I received an error message while doing Build Android App Bundle... via google menu.

FileNotFoundException: Asset pack directory doesn't exist
Google.Android.AppBundle.Editor.AssetPackConfig.AddAssetsFolder (System.String assetPackName, System.String assetsFolderPath, Google.Android.AppBundle.Editor.AssetPackDeliveryMode deliveryMode) (at Assets/GooglePlayPlugins/com.google.android.appbundle/Editor/Scripts/AssetPackConfig.cs:117)
Google.Android.AppBundle.Editor.Internal.Config.SerializationHelper.Deserialize (Google.Android.AppBundle.Editor.Internal.Config.SerializableAssetPackConfig config) (at Assets/GooglePlayPlugins/com.google.android.appbundle/Editor/Scripts/Internal/Config/SerializationHelper.cs:189)
Google.Android.AppBundle.Editor.AssetPacks.AssetPackConfigSerializer.LoadConfig () (at Assets/GooglePlayPlugins/com.google.android.appbundle/Editor/Scripts/AssetPackConfigSerializer.cs:52)
Google.Android.AppBundle.Editor.Internal.AppBundlePublisher.Build () (at Assets/GooglePlayPlugins/com.google.android.appbundle/Editor/Scripts/Internal/AppBundlePublisher.cs:134)
Google.Android.AppBundle.Editor.Internal.AppBundleEditorMenu.BuildAndroidAppBundle () (at Assets/GooglePlayPlugins/com.google.android.appbundle/Editor/Scripts/Internal/AppBundleEditorMenu.cs:66)

Even though I have added my assets through the asset delivery settings.
![image](https://user-images.githubusercontent.com/11439797/165666937-93aafebb-da35-46c8-83d2-f612b3ba6846.png)

**Comment by auXtern** [comment]
![image](https://user-images.githubusercontent.com/11439797/165876889-2654a268-2a57-42b5-ab24-637a17c8db16.png)
Problem solved, this happens when the project is opened in another environment. So that the temporary assets listed in the PlayAssetPackConfig.json file are no longer found. The solution is to delete the PlayAssetPackConfig.json file and do a build again via the Google menu.

**Comment by ismail-koroglu** [comment]
@auXtern thanks for reply. You saved me a lot of time.
