### ISSUE TITLE
Play Asset Delivery - Cant accesing active request

### ISSUE THREAD

**Issue by asrakan** [google/play-unity-plugins#18]
When I do not cache or restart the game I can't access the current active Bundle Requests from the API

**Comment by thanwah** [comment]
Thank you @asrakan for filing this issue.

@jamcohen, can you please take a look when we're back from holiday next week?

**Comment by jamcohen** [comment]
Hi @asrakan,

Thanks again for raising this issue. I've got a couple questions that'll help me diagnose the problem.
Could you describe the behavior you're seeing in more detail?
When you call RetrieveAssetBundleAsync, are you checking the returned request over time to see if it succeeds?
Does the status of that request ever change to "Loaded"?
Are there any debug logs you can share?

Best,
Jake Cohen

**Comment by asrakan** [comment]
Actually I am handling the logics, but when there are some certain problems in-game I reset the application so all of the coroutines and my caches are get clean. Due to this, I can't reach the currently active requests I made before which are still loading/loaded, I want to access them.

Here is the my code line;
` public IEnumerator DownloadCoroutine(AssetBundleRequest request)
        {
            Debug.LogError("dowload coroutine : " + request.AssetBundleData.BundleName);
            request.TriedCount++;
            if (request.TriedCount >= MaxPLayServiceAssetDeliveryTryCount)
            {
                request.AssetBundleData.BundleStatu = BundleStatus.Failed;
                request?.ErrorCallback(request);
                yield break;
            }
            try
            {
                if (request.PlayAssetBundleRequest == null)
                {
                    request.PlayAssetBundleRequest = PlayAssetDelivery.RetrieveAssetBundleAsync(request.AssetBundleData.BundleName);
                }
            }
            catch (Exception ex)
            {
                string errorMessage = "BUNDLE SYSTEM - WILL BE HALTED - Play Service delivery problem. TRY COUNT : " + request.TriedCount + " Error : " + ex.Message + "..Status : " + request.PlayAssetBundleRequest.Status + ". Bundle name : " + request.AssetBundleData.BundleName;
                Debug.LogError(errorMessage);
                Crashlytics.LogException(new Exception(errorMessage));
                GameAnalyticsSDK.GameAnalytics.NewErrorEvent(GameAnalyticsSDK.GAErrorSeverity.Critical, errorMessage);
                request.EmptyMonoBehavior.StartCoroutine(HaltRequest(request));
                yield break;
            }
            yield return new WaitForEndOfFrame();
            if (BundleDownloadErrorControl(request))
            {
                yield break;
            }
            //Waiting for play service to handle reuqest
            while (!request.PlayAssetBundleRequest.IsDone)
            {
                if (BundleDownloadErrorControl(request))
                {
                    yield break;
                }
                switch (request.PlayAssetBundleRequest.Status)
                {
                    case AssetDeliveryStatus.Pending:
                        break;
                    case AssetDeliveryStatus.Retrieving:
                        request.AssetBundleData.BundleStatu = BundleStatus.Downloading;
                        request.DownloadProgress = request.PlayAssetBundleRequest.DownloadProgress;
                        AssetBundleDownloadPanel.UpdateDataStatic(request.DownloadProgress, request.AssetBundleData.Size, request.AssetBundleData.BundleName, Color.green);
                        break;
                    default:
                        break;
                }
                request.DownloadProgress = request.PlayAssetBundleRequest.DownloadProgress;
                yield return new WaitForEndOfFrame();
            }
            if (BundleDownloadErrorControl(request))
            {
                yield break;
            }
            else
            {
                //Writing like this to simplfy 
                if (request.RequestType < BundleRequestTypes.Load)
                {
                    request.PlayAssetBundleRequest.AssetBundle.Unload(true);
                    request.AssetBundleData.BundleStatu = BundleStatus.Downloaded;
                    request.ResultCallback(request);
                }
                else
                {
                    request.AssetBundleData.Bundle = request.PlayAssetBundleRequest.AssetBundle;
                    request.AssetBundleData.BundleStatu = BundleStatus.Loaded;
                    request.ResultCallback(request);
                }
            }

        }`

**Comment by jamcohen** [comment]
Ah, I see. So the issue is that you lose the reference to the PlayAssetBundleRequest and then when you call RetrieveAssetBundleAsync you get an exception because thats asset pack request is still in progress.

I'll explore having that method return the active request instead of throwing that exception. 

In the meantime could you maintain a dictionary of request keyed by asset pack names? Then, in the catch block for that exception you could reference the last active request stored in the dictionary. Would that work?

**Comment by asrakan** [comment]
Hello, I am basically maintaining the problem for now, but it would be better to have returning active request
