### ISSUE TITLE
Asset Delivery v1.8.0 launch issue

### ISSUE THREAD

**Issue by Hoss42** [google/play-unity-plugins#188]
1.8.0 paired with the latest version of google play games plugin causes apps failing to launch after a successful build in unity 2021.3.6f1. downgrading to play asset delivery version 1.7.0 resolves the issue.

With this issue I was unable to retrieve any logs in android logcat

**Comment by uniquecorn** [comment]
facing this issue as well

**Comment by uniquecorn** [comment]
resolved by rolling back to 1.7.0

**Comment by isurfraz** [comment]
This is not closed. Having to roll back is not a resolution - 1.8+ needs to be fixed
