### ISSUE TITLE
Could not find com.google.games:gpgs-plugin-support:0.11.01

### ISSUE THREAD

**Issue by suchiz** [google/play-unity-plugins#196]
Hello everyone, I come from https://github.com/googlesamples/unity-jar-resolver/issues/535 if you need the full context of the issue.

**To resume:**
I want to use Google Play Services and the  In-App update feature from Google Play Plugins.
I had some Android dependencies conflicts while using both. Both are working fine independtly but cannot stick together.

With some help from the linked github issue, this  `Android dependencies  conflicts` part is now solved but comes with another issue which is an error while building the game.

**To reproduce the issue (also you can check the linked issue):**
**Unity editor version:** 2020.3.30f1
**Google Play Services:**  https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/current-build/GooglePlayGamesPlugin-0.11.01.unitypackage.
**Google App Update:** https://github.com/google/play-unity-plugins/releases/download/v1.8.0/com.google.play.appupdate-1.8.0.unitypackage

**The full build error log:**
```
* What went wrong:
Could not determine the dependencies of task ':unityLibrary:compileReleaseAidl'.
> Could not resolve all task dependencies for configuration ':unityLibrary:releaseCompileClasspath'.
   > Could not find com.google.games:gpgs-plugin-support:0.11.01.
     Required by:
         project :unityLibrary
 ```
 
Steps: 
1. Download both package: https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/current-build/GooglePlayGamesPlugin-0.11.01.unitypackage and https://github.com/google/play-unity-plugins/releases/download/v1.8.0/com.google.play.appupdate-1.8.0.unitypackage.
2. Create a new 2D project with Unity 2020.3.30f1
3. Switch plateform to Android
4. Import `GooglePlayGamesPlugin-0.11.01.unitypackage` in project
5. Import `com.google.play.appupdate-1.8.0.unitypackage` in project
6. Enable `Custom Main Gradle Template` and `Custom Gradle Properties Template` in `Build settings`
7. Resolve Android dependencies with `External Dependencies Manager`
8. Try to build APK and get the build error.

Thanks !

**Comment by anycolourulike** [comment]
Double check that you have only one version of the plugins but really it
seems that Unity is reliably crap at building for Google Play unless you
use latest recommended Unity version, highlighted in unity hub.

**Comment by suchiz** [comment]
Hello @anycolourulike , thanks for your time.

As the issue can be reproduced from scratch even with the latest unity version, I dont think I could have 2 different version of the plugins. With a brand new project, I ensure to only have one version of each.
Or isn't it what you were expecting from me to do ?

**Comment by suchiz** [comment]
I am using a CI to publish my game to the store. I will try the work around manually but it isnt a sustainable solution.
I also tried with the 2021.3.8f1 editor version, and didn't implement any package. I really just tryna import them and just build...

What are the steps you did to get a successful build ?

**Comment by anycolourulike** [comment]
I take it you are using addressables?

https://forum.unity.com/threads/gradle-build-fail-with-adressables.975969/

This thread might be of some use.

I'm currently away from my PC. Any indicators in the "what went wrong" part
of the  error message.

Also worth taking this issue to Unity forums. There was a bug with unity
and the android tools version that was fixed by rolling back to 3.4.0 but
that shouldn't be an issue in the latest version of Unity.

**Comment by anycolourulike** [comment]
Also Unity downloads the dependencies it needs so worth disabling and
firewalls etc. Are you on a personal PC or a company computer?

**Comment by suchiz** [comment]
I am using adressables! It is on my PC, I will give a shot tomorrow ! I'll let you know

**Comment by anycolourulike** [comment]
Addressables are a bit awkward at first as they mix up and asset bundle
guides and you need to write your own level selection logic. The only
videos are about how "it's so easy just refactor your project" I'll write
out a few steps I followed for you tomorrow

**Comment by anycolourulike** [comment]
Check out the Bronson clip
https://youtu.be/_2Y2snH_Cg4

Also the Addressables Clip:
https://youtu.be/sjNL41vlC0o

**Comment by suchiz** [comment]
I tried everything on this thread, and nothing was working for me.
 But i've now installed Unity 2021.3.9f1 on a brand new environnement, and indeed, it built. So it might really be caused by Adressables.
 
 I only watched the Addressable Clip, but Im not sure what you're expecting from me. Try to create an Asset bundle to gather GPS and App update in the same asset?
 
Anyway, I think the issue is a little bit too complated for me. I will just give up and stick with GPS only, as it is already working fine on my game currently. I'll use something else for the app update...

Thank you so much for your help and time, I'll just whine on my side !

**Comment by anycolourulike** [comment]
I see the original message is that the same error as in the 2021 build?

**Comment by suchiz** [comment]
Yes it is

**Comment by hamzabenyahya126** [comment]
i was facing some errors with plugin version 0.11 but when i delete it and download version 0.10.14 and change the code the be for 0.10.14 everythings work (login to google play, leaderboard and achievement).

**Comment by snlehton** [comment]
For me, after upgrading for some reason the `\Assets\GooglePlayGames\com.google.play.games\Editor\GooglePlayGamesPluginDependencies.xml` contained `<repository>Packages/com.google.play.games/Editor/m2repository</repository>` when it should have been `<repository>Assets/GooglePlayGames/com.google.play.games/Editor/m2repository</repository>`

Fixing that allowed the Play games plugin be included in the build.

If you force resolve the Android EDM, you will see a warning about this invalid repo. It should really be an error IMO. Pretty critical issue if the Android lib is not included...
