### ISSUE TITLE
UNITY: java.lang.ClassNotFoundException: com.google.android.play.core.review.ReviewManagerFactory

### ISSUE THREAD

**Issue by chomi3** [google/play-unity-plugins#208]
Hey. 

I'm encountering the following error in android build in Unity:

Error Unity AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.play.core.review.ReviewManagerFactory
Error Unity java.lang.ClassNotFoundException: com.google.android.play.core.review.ReviewManagerFactory
Error Unity 	at java.lang.Class.classForName(Native Method)
Error Unity 	at java.lang.Class.forName(Class.java:400)
Error Unity 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
Error Unity 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source)
Error Unity 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source)
Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:101)
 Error Unity 	at android.os.Looper.loop(Looper.java:156)
Error Unity 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source)
Error Unity Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.play.core.review.ReviewManagerFactory" on path: DexPathList[[zip file "/data/app/com.HamsterOnCoke.MAZAICA-2/base.apk"],nativeLibraryDirectories=[/data/app/com.HamsterOnCoke.MAZAICA-2/lib/arm64, /data/app/com.HamsterOnCoke.MAZAICA-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /sys

1. I'm not using proguard
2. I'm not using minify
3. I've checked (1) and (2) thorough the game, and no proguard is being used.
4. Dependencies are properly set in Assets/Plugins/Android/mainTemplate.gradle . 
5. I set the dependencies manually, or using Dependencies Resolver force resolve. Same results.
6. No matter how I build the build (aab, apk), the classes are NOT included to .dex files.
7. Uploading the build to Internal App Sharing doesn't help either

I'm clueless.
Have no idea what I'm doing wrong, or how I can debug this, to find the cause of the issue. Any ways to get to logs, to see why the classes are getting their way into the build?

Any help is much appreciated.

Thanks
Cheers
Mike

**Comment by rafanoel** [comment]
It seems like the review library is not part of your build (apk, aab). Which play core version are you using?

**Comment by chomi3** [comment]
Hey,

I'm using:

    implementation 'com.google.android.play:core-common:2.0.0' 
    implementation 'com.google.android.play:review:2.0.0'

**Comment by chomi3** [comment]
Ok it looks like I've finally nailed the issue.
One of the libraries from my publisher is overriding the mainTemplate.gradle file on build start...
Oh lord.

Sorry for the trouble.
I'm closing the issue.
