### ISSUE TITLE
How to Read Raw Asset using Play Asset Delivery at Runtime? 

### ISSUE THREAD

**Issue by heshuimu** [google/play-unity-plugins#21]
In my project, I have files that are not assets recognized by Unity (and thus cannot be packed into a Unity AssetBundle). Currently, I put them in StreamingAssets, which is then packed into OBB, and I read them back from OBB at runtime. 

I found from the API that I can create a Play Asset Pack with raw assets (i.e. any arbitrary file, assuming I understood it correctly).
https://developer.android.com/reference/unity/class/Google/Android/AppBundle/Editor/AssetPack#assetpackdirectorypath
https://github.com/google/play-unity-plugins/blob/cf4704e71a4ced934d472e8db749d33770c61cbe/GooglePlayPlugins/com.google.android.appbundle/Editor/Scripts/AssetPack.cs#L62-L69

But then I found that the Runtime API does not have a way to read those raw assets back. I can only find `PlayAssetBundleRequest` class which only has an `AssetBundle` property. 
https://developer.android.com/reference/unity/class/Google/Play/AssetDelivery/PlayAssetBundleRequest

I looked everywhere and did not find any relevant API. Maybe I am not looking very closely? Thanks in advance!

**Comment by jamcohen** [comment]
Thanks for raising this issue. Currently the runtime API lags behind the packaging API a bit. We are working on updating the runtime API with a method that allows you to access the raw assets inside of those packs, but that functionality isn't supported yet.

In the meantime as a workaround/hack, you can use Unity's [TextAsset](https://docs.unity3d.com/ScriptReference/TextAsset.html) to have GameObjects reference arbitrary files. Then you can package those GameObjects in AssetBundles and access the files using TextAsset.bytes.

**Comment by heshuimu** [comment]
Thank you for clarifying. I am currently not there yet with my project where lacking this feature would be an issue so I can wait for now.

**Comment by jamcohen** [comment]
Update: We added experimental support for this in the [v1.1.1 release](https://github.com/google/play-unity-plugins/releases). If you want to give it a try, you can enable the PLAY_ASSET_DELIVERY_EXPERIMENTAL preprocessor definition in player settings (see the "Platform custom #defines" section [here](https://docs.unity3d.com/Manual/PlatformDependentCompilation.html) for how to do that)

**Comment by shwuhk** [comment]
@jamcohen May I know how to get Raw Asset now?

**Comment by jamcohen** [comment]
The runtime documentation is available [here](https://developer.android.com/guide/playcore/asset-delivery/integrate-unity?language=api). [Here's](https://developer.android.com/guide/playcore/asset-delivery/integrate-unity?language=api#load-assets-into-memory) the part about reading those files from disk.

To load a raw asset you should:
"Use `PlayAssetPackRequest.GetAssetLocation()` to get an [`AssetLocation`](https://developer.android.com/reference/unity/class/Google/Play/AssetDelivery/AssetLocation#classGoogle_1_1Play_1_1AssetDelivery_1_1AssetLocation) object. This provides the path, offset, and size of the asset so that it can be loaded from disk."

**Comment by shwuhk** [comment]
@jamcohen Thanks for your help. We get the AssetLocation object but find that we can't load that file out. It would be good if you could show us some light.

This is the { path / size / offset } of the AssetLocation object  { /data/app/com.DefaultCompany.TestAB-KRpgbnLxvKt8DzJ3vu3IKg==/split_assets.apk / 620847 / 2188 }. This should be a simple .txt file but we find that we could not read this file out with Readerstream using the path above.

**Comment by jamcohen** [comment]
Here's an example using a file stream to load the text into a string:
````
FileStream assetFileStream = File.OpenRead(assetLocation.Path);
byte[] buffer = new byte[assetLocation.Size];
assetFileStream.Seek((long) assetLocation.Offset, SeekOrigin.Begin);
assetFileStream.Read(buffer, /* offset= */ 0, buffer.Length);
string fileContents = Encoding.UTF8.GetString(buffer, 0, buffer.Length);
````

Are you doing something similar?

**Comment by shwuhk** [comment]
This really help!
Thanks!!

**Comment by jamcohen** [comment]
Happy to help! I'll close this issue, but feel free to reopen if you're still having trouble.
