### ISSUE TITLE
Play Billing - Declined Deferred purchases never return as failed.

### ISSUE THREAD

**Issue by sampsao** [google/play-unity-plugins#22]
Hi,

I implemented your extended version of Unity IAP to handle deferred purchases/slow credit card transactions in our game. The plugin seems to be working fine otherwise but I encountered a problem while testing deferred purchases that decline after a few minutes. After the client receives a deferred purchase the plugin never seems to inform when the purchase actually fails. This is a problem as we want the user to be able to start and handle only one purchase at a time. Because the failure callback never returns the client waits infinitely for a message to clear the purchase from the queue. The flow goes like this:

1. Start IAP with slow test card
2. Show info for player that the purchase is still being handled, they can continue playing
3. Client has a deferred purchase stored and prevents any further purchases before the first one is handled properly.
4. The purchase is left hanging so I can never "finish" the transaction and allow the player to initiate other purchases.

Also if I restart the game, the plugin doesn't inform about any pending transactions in this case. And if I try to purchase the same item again it immediately returns with a "duplicate transaction"-failure. I noticed that the purchase does clear automatically after a while so I can initiate the purchase later without duplicate errors.
Is this intended behaviour? From my point of view the deferred purchases should always invoke the failure callback whenever the transaction is declined and I should be able to clear that transaction from any sort of queue so the user can try to initiate that purchase again if they so choose.

**Comment by sampsao** [comment]
Hi,

Additional information about the deferred purchases. If I start a slow test purchase that will be approved after a few minutes and restart the game before that purchase is finished, that purchase does not return a deferred purchase callback or any kind of pending information.
I think it would be useful to know if there are deferred/slow purchases in the queue, so that one could display it somehow for the player or even restrict the player from making additional purchases while the first one is still being handled.

**Comment by sampsao** [comment]
Ok, I just found out these threads from your native version of the billing library
https://github.com/android/play-billing-samples/issues/272
https://issuetracker.google.com/issues/149668311
Seems like something that should be fixed from the core of the billing lib. Very frustrating from a developer's point of view when you can not know the exact situations when these kind of pending purchases fail especially since it's someones money we're handling here. These will for sure result in unnecessary support requests down the line, which is a shame as these could be informed quite easily if we would just have the data. Hoping for improvements on this.
I'm able to work around these limitations even though it's not optimal. One big improvement for the developer tools would also be to standardise the time it takes for the slow test payment to decline. Now it might be anything between 15 minutes to hours to decline. It makes it very hard, if not impossible, to test different types of corner cases that some users will inevitably encounter in real life scenarios.
I'd still be happy to hear back from you if there's something I've misunderstood /overlooked or if you have any insights to give me regarding these implementations.

**Comment by Qing451800** [comment]
You're right. The issue goes beyond this Unity wrapper but lives inside the PBL core library. We're working actively to resolve the caching issue. Please follow https://issuetracker.google.com/issues/73982566 for updates. 

This issue will be closed as the fix cannot happen here. Thanks for reaching us.

**Comment by AdamStepinski0** [comment]
In my case, Transaction was declined because Unity's project didn't have license key set in Google Play Services
![image](https://github.com/google/play-unity-plugins/assets/68370474/d95e48cf-410f-4e77-9f69-27bd568092ff)
this can be found in Google Play Console > [app] > Monetisation > Monetisation Setup
