### ISSUE TITLE
Google packages For Unity Need To Update 

### ISSUE THREAD

**Issue by SayedKotb** [google/play-unity-plugins#245]
![Screenshot 2024-06-19 034903](https://github.com/google/play-unity-plugins/assets/58949319/4d9823c8-d8a8-4cf7-99a6-23cae1cd7ea5)
The current version of the in-app update package for Unity is not compatible with Android 14. We need a newer version to be compatible with it and fix this bug, I think there are more Unity packages that need to be updated as well .

**Comment by uniquecorn** [comment]
I'm literally blocked from uploading new builds because of this.

**Comment by psstevenchan** [comment]
+1

**Comment by Romanbard** [comment]
+1

**Comment by Romanbard** [comment]
@uniquecorn Can you give me a little more detail about the method you mentioned?

**Comment by uniquecorn** [comment]
@Romanbard Just bump the version in the Dependencies.xml file.

**Comment by flixbeat** [comment]
> I bumped the dependency manually in the plugin and got it to work. Not a real fix but works for now.

Hi, where can I find this "Dependencies.xml" file? I don't find it anywhere in my project files.
![image](https://github.com/google/play-unity-plugins/assets/12845479/7d38c398-dde7-4eda-859e-5a8273761473)

**Comment by cookapps-shkim2** [comment]
@flixbeat I modified it as below.
but, if you run Android Resolve on EDM, you are back to square one...

Assets/../ProjectSettings/AndroidResolverDependencies.xml
...
<package>com.google.android.play:app-update:2.1.0</package>
...

Assets/Plugins/Android/mainTemplate.gradle
...
implementation 'com.google.android.play:app-update:2.1.0' // Packages/com.google.play.appupdate/Editor/Dependencies.xml:3
...

**Comment by sopo-c** [comment]
write on github: Thanks for raising the issue, we've fixed it and released new versions of Play Asset Delivery, Play In-App Review, Play In-App Update and Play Integrity API here: https://developers.google.com/unity/packages#google_play.
