### ISSUE TITLE
I want to adapt to targetSdkVersion34 now, where do I need to upgrade.

### ISSUE THREAD

**Issue by LBCross** [google/play-unity-plugins#248]
![image](https://github.com/user-attachments/assets/811fb333-2ffb-49c7-80de-825d2e58a1f5)
I want to adapt to targetSdkVersion34 now, where do I need to upgrade

**Comment by sopo-c** [comment]
You can find the latest versions of the plugins here: https://developers.google.com/unity

**Comment by LBCross** [comment]
Unity 2019.4.36 version, Play Asset Delivery will crash when initializing, but I don’t want to upgrade Unity, so I decompiled the classes.jar in the com.google.android.play.core-1.10.3.aar file, modified the source code, and then decompiled it back, which solved the problem.

![image](https://github.com/user-attachments/assets/bbdd6746-7c91-4c62-b91e-bffd6d9cea14)

Crash for me
`2024-07-16 14:25:58.589 23619-23746/com.gravity.roo.sea E/CRASH: Tombstone written to: /storage/emulated/0/Android/data/com.gravity.roo.sea/files/tombstone_00
2024-07-16 14:25:58.589 23619-23746/com.gravity.roo.sea A/gravity.roo.sea: java_vm_ext.cc:591] JNI DETECTED ERROR IN APPLICATION: JNI FindClass called with pending exception java.lang.NoSuchMethodError: No interface method getPackStates(Ljava/util/List;)Lcom/google/android/play/core/tasks/Task; in class Lcom/google/android/play/core/assetpacks/AssetPackManager; or its super classes (declaration of 'com.google.android.play.core.assetpacks.AssetPackManager' appears in /data/app/~~UMxiZdOm2SY0LhjWR5HpdQ==/com.gravity.roo.sea-sMoDrXJHSZvR7Ofbr9cAPg==/base.apk!classes3.dex)
    java_vm_ext.cc:591]   at void com.unity3d.player.a.a(java.lang.String[], com.unity3d.player.IAssetPackManagerStatusQueryCallback) ((null):-1)
    java_vm_ext.cc:591]   at void com.unity3d.player.PlayAssetDeliveryUnityWrapper.getAssetPackStates(java.lang.String[], com.unity3d.player.IAssetPackManagerStatusQueryCallback) ((null):-1)
    java_vm_ext.cc:591]   at void com.unity3d.player.PlayAssetDeliveryUnityWrapper.getAssetPackState(java.lang.String, com.unity3d.player.IAssetPackManagerStatusQueryCallback) ((null):-1)
    java_vm_ext.cc:591]   at boolean com.unity3d.player.UnityPlayer.nativeRender() ((null):-2)
    java_vm_ext.cc:591]   at boolean com.unity3d.player.UnityPlayer.access$300(com.unity3d.player.UnityPlayer) ((null):-1)
    java_vm_ext.cc:591]   at boolean com.unity3d.player.UnityPlayer$e$1.handleMessage(android.os.Message) ((null):-1)
    java_vm_ext.cc:591]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
    java_vm_ext.cc:591]   at boolean android.os.Looper.loopOnce(android.os.Looper, long, int) (Looper.java:224)
    java_vm_ext.cc:591]   at void android.os.Looper.loop() (Looper.java:318)
    java_vm_ext.cc:591]   at void com.unity3d.player.UnityPlayer$e.run() ((null):-1)
    java_vm_ext.cc:591] 
    java_vm_ext.cc:591]     in call to FindClass
    java_vm_ext.cc:591]     from boolean com.unity3d.player.UnityPlayer.nativeRender()
2024-07-16 14:25:58.643 23619-23746/com.gravity.roo.sea A/gravity.roo.sea: runtime.cc:691] Runtime aborting --- recursively, so no thread-specific detail!`
