### ISSUE TITLE
Why discontinuing github / oupm ?

### ISSUE THREAD

**Issue by calumma-robert** [google/play-unity-plugins#253]
`New versions of Play Unity plugins are not published on Github any more. Latest versions should be downloaded from the [[Google APIs for Unity]](https://developers.google.com/unity) page.`

Why?

Other google services finally move steps ahead and start using it (like AdMob) and now you decide, well lets get back to the old crappy .unitypackage via manual updates? It would really help if you guys team up and think about an uniform solution...

**Comment by pauvallespi** [comment]
Hi! Just wanted to let you know that we support GitHub again, as well as OpenUPM! We have divided the plugins in different repositories:
- https://github.com/google/play-appbundle-unity
- https://github.com/google/play-core-unity
- https://github.com/google/play-common-unity
- https://github.com/google/play-integrity-unity
- https://github.com/google/play-asset-delivery-unity
- https://github.com/google/play-in-app-reviews-unity
- https://github.com/google/play-in-app-updates-unity/

You can also find them on OpenUPM (e.g. https://openupm.com/packages/com.google.play.review/).

**Comment by calumma-robert** [comment]
Thank you!
