### ISSUE TITLE
On Demand module Local testing is not possible in universal apk

### ISSUE THREAD

**Issue by Sortexsvg** [google/play-unity-plugins#32]
I am trying to create universal apk and test the on demand module. I have used flag --local-testing and -mode=universal. But error while retriving the pack. Is there any solution?

**Comment by jamcohen** [comment]
How are you installing the pack? Are you using `bundletool --install-apk`, or using `adb` directly?

**Comment by Sortexsvg** [comment]
I tried both the ways. 

When I used install-apks command commadline, it gave error . 

When I used adb command the pack unavailable error came in device

**Comment by jamcohen** [comment]
I'm talking to the bundletool team about this, but my guess is that this isn't something we support.

My understanding is that the main benefit of universal apks is that they can be installed without using bundletool (i.e via adb). Local testing relies on `bundletool install-apks` to install the asset packs in the right locations. If you're using `bundletool install-apks` you shouldn't need to use universal mode.

Is there some other benefit of universal apks that I'm missing?
Is there anything preventing you from testing without the `-mode=universal` flag?

**Comment by Sortexsvg** [comment]
Thanks for your Information. You are not missing any benefits of universal apk. I asked because if universal apk support On Demand feature,then I can directly pass the apk to QC team.
