### ISSUE TITLE
In-App Review not showing

### ISSUE THREAD

**Issue by robson-work** [google/play-unity-plugins#38]
I'm having some trouble getting the In-App Review to work.
I followed the instructions and used the sample code. It all executes, but nothing appears on screen. There is no error on log.
Any ideas what I could be missing?

**Comment by jamcohen** [comment]
Thanks @robson-work for reaching out. There are a couple reasons why the dialog might not show up.
Have you seen [these testing instructions](https://developer.android.com/guide/playcore/in-app-review/test)?
That doc lists out recommended ways to test In-App Review along with common troubleshooting tips.

**Comment by robson-work** [comment]
@jamcohen Yes, I followed the instructions. I have the app in internal testing.
This is the code I am using. It executes all the way to the end.
I even get a event from another plugin I have that triggers when the app goes to background, so it seems like it starts to show the in-app review, but it never appears.

`private IEnumerator requireRate()
    {
        ReviewManager _reviewManager;
        _reviewManager = new ReviewManager();
        var requestFlowOperation = _reviewManager.RequestReviewFlow();
        yield return requestFlowOperation;
        if (requestFlowOperation.Error != ReviewErrorCode.NoError)
        {
            Debug.Log("Erros - " + requestFlowOperation.Error.ToString());
            yield break;
        }
        PlayReviewInfo _playReviewInfo = requestFlowOperation.GetResult();

        Debug.Log("review info " + _playReviewInfo.ToString());

        var launchFlowOperation = _reviewManager.LaunchReviewFlow(_playReviewInfo);
        yield return launchFlowOperation;
        _playReviewInfo = null; // Reset the object
        if (launchFlowOperation.Error != ReviewErrorCode.NoError)
        {
            Debug.Log("Error2 - " + requestFlowOperation.Error.ToString());
            yield break;
        }

        Debug.Log("Flow finished");

    }`

**Comment by rafanoel** [comment]
Your code looks good.

Could you please double check if you don't have a review for that app with that account? You will need to go to the Play Store and manually remove the review if its already there.

Another thing to check, is the account that you are using the primary account in the Play Store?

**Comment by robson-work** [comment]
> Another thing to check, is the account that you are using the primary account in the Play Store?

Maybe this is the issue, because I asked another person on the team to test and it worked normally.

**Comment by rafaelf82** [comment]
> Another thing to check, is the account that you are using the primary account in the Play Store?

Does it have to be the primary account?

I'm internal tester on the company I work and I'm trying to implement this and nothing shows up.

This is being extremely difficult to test, no errors, no message, it just doesn't show.

**Comment by rafanoel** [comment]
@robson-work thanks for verifying.

**Comment by rafanoel** [comment]
@rafaelf82 

> Does it have to be the primary account?
Yes, please use your primary account.

> 
> I'm internal tester on the company I work and I'm trying to implement this and nothing shows up.
Instead of using your corp account, please use a gmail account.

**Comment by rafanoel** [comment]
I am closing this issue since original comment has been resolved. @rafaelf82  please let's follow up your issue on your own [issue 49](https://github.com/google/play-unity-plugins/issues/49).
