### ISSUE TITLE
In-app Review not showing

### ISSUE THREAD

**Issue by catinjar** [google/play-unity-plugins#39]
I implemented the feature and try to request and launch in-app review by clicking debug button. I deploy the build locally and my Google Play account is in the list of internal testers. Documentation says that "The quota limits are not enforced if the app is downloaded from the internal test track", so, I guess, triggering this by clicking debug button is fine.

It worked just fine only the first time. Review activity showed up and I was able to leave my review. I deleted the review. But after that I wasn't able to reproduce this. I tried different Google Play accounts and different devices.

It looks like activity tries to show up and then immediately closes, and the game pauses for a moment.

Both RequestReviewFlow and LaunchReviewFlow finish successfully every time without errors.

I tried to look into Logcat logs, but only errors I can see is stuff like this, which is not specific to this problem:
`
E: Error inserting period=6580000 preferred_charging_state=1 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService required_network_type=0 runtime=1598593194053 required_idleness_state=0 source=16 service_kind=0 target_package=com.google.android.gms persistence_level=1 source_version=203019000 last_runtime=0 user_id=0 job_id=-1 requires_charging=0 tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG flex_time=3289000 task_type=0 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}}
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:796)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1564)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1433)
        at arll.a(:com.google.android.gms@203019028@20.30.19 (100400-326531024):122)
        at arki.a(:com.google.android.gms@203019028@20.30.19 (100400-326531024):183)
        at arki.a(:com.google.android.gms@203019028@20.30.19 (100400-326531024):22)
        at arki.a(:com.google.android.gms@203019028@20.30.19 (100400-326531024):178)
        at argl.run(:com.google.android.gms@203019028@20.30.19 (100400-326531024):9)
        at ssz.b(:com.google.android.gms@203019028@20.30.19 (100400-326531024):12)
        at ssz.run(:com.google.android.gms@203019028@20.30.19 (100400-326531024):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at sza.run(:com.google.android.gms@203019028@20.30.19 (100400-326531024):0)
        at java.lang.Thread.run(Thread.java:764)
`

What might be the problem? My implementation is identical to the documentation and it worked for the first time (maybe it was random luck). I checked all trobleshooting tips.

**Comment by binouze** [comment]
As for the issue https://github.com/google/play-unity-plugins/issues/42#issue-688048192, would be good to know if the review flow is not shown to fallback on the play store link.

**Comment by rafanoel** [comment]
Thanks for reaching out @catinjar. The documentation about the quota is right.

When you try with other different accounts, could you please assign them as the primary account in the Play Store? the easiest way is to remove any other account in the smartphone when you are trying it.

**Comment by catinjar** [comment]
Thanks for the response @rafanoel.

I tried to switch the primary account on my device as you suggested. And I asked a tester to check this on theirs device too. But the activity is still not shown on any device/account.

Also, I've waited for a weekend to try this again, but result was the same. How long should I wait to be sure that the quota in not a problem here?

**Comment by rafanoel** [comment]
@catinjar getting back to your first comment, I noticed that you are using the internal test track, could you double check that you are using the internal test track? normally, on this track you won't be able to leave a review.

**Comment by neosVN-hungvt** [comment]
An instance of PlayAssetDeliveryEventHandler is already present in the scene. Self-destructing...
Google.Play.Core.Internal.PlayCoreEventHandler:Awake()
UnityEngine.GameObject:AddComponent()
Google.Play.Review.ReviewManager:.ctor()
ReviewPopup:RequestStoreReviewAndroid()
UnityEngine.Events.UnityAction:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.EventSystems.EventFunction`1:Invoke(T1, BaseEventData)
 UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents()
UnityEngine.EventSystems.StandaloneInputModule:Process()

I'm experiencing this, the review dialog show once then I install other version of the app then the error above show every time I call method to show review dialog.
my implement here:
`private void RequestStoreReviewAndroid()
    {
        var reviewManager = new ReviewManager();

        // start preloading the review prompt in the background
        var playReviewInfoAsyncOperation = reviewManager.RequestReviewFlow();

        // define a callback after the preloading is done
        playReviewInfoAsyncOperation.Completed += playReviewInfoAsync =>
        {
            if (playReviewInfoAsync.Error == ReviewErrorCode.NoError)
            {
                // display the review prompt
                var playReviewInfo = playReviewInfoAsync.GetResult();
                reviewManager.LaunchReviewFlow(playReviewInfo);
            }
            else
            {
                // handle error when loading review prompt
            }
        };
    }`

please help!

**Comment by rafanoel** [comment]
@neosVN-hungvt are you using the [internal testing](https://play.google.com/console/about/internal-testing/) track?

**Comment by neosVN-hungvt** [comment]
@rafanoel yes, I'm using internal testing

**Comment by rafanoel** [comment]
@neosVN-hungvt that's good, be sure to distribute the app through the internal testing track. Sometimes the account is using that track, but we side-load the app instead of pushing the app through the track. 

Please take a look at the [troubleshooting](https://developer.android.com/guide/playcore/in-app-review/test#troubleshooting) section, there are a couple of things like using the primary account, type of account, among other things that you could check.

**Comment by catinjar** [comment]
@rafanoel I was able to make it work in the internal test track but I have to clear data for Google Play app on my device every time.

Thanks for your help, I'm closing this issue.
