### ISSUE TITLE
AndroidManifest.xml com.google.android.gms.instant.flavor = 1337

### ISSUE THREAD

**Issue by megasoft78** [google/play-unity-plugins#4]
Hi,
it seems this meta-data is required for the Instant version but not for the Installed one:
https://developer.android.com/topic/google-play-instant/instant-play-games-checklist

`<meta-data android:name="com.google.android.gms.instant.flavor" android:value="1337"/>
`

It is possible to automatically add it during the build?

**Comment by thanwah** [comment]
Thanks @megasoft78 for the suggestion! @jamcohen is looking into implementing this.

**Comment by jamcohen** [comment]
Thanks again for suggesting this.

[v1.1.0](https://github.com/google/play-unity-plugins/releases/tag/v1.1.0) now includes a checkbox in build settings for toggling whether a game is a full "instant play" game. Enabling that checkbox will automatically add the metadata:
`<meta-data android:name="com.google.android.gms.instant.flavor" android:value="1337"/>`


<img width="404" alt="Screen Shot 2020-05-11 at 4 29 20 PM" src="https://user-images.githubusercontent.com/4805315/81621991-b6433980-93a4-11ea-81d1-c8b9072633b0.png">
