### ISSUE TITLE
Play Asset Delivery - can't use profiler

### ISSUE THREAD

**Issue by TutoMikDab** [google/play-unity-plugins#40]
Using the "Build and Run" option from the "Google" menu bar item while having the "development" and "autoconnect profiler" checkboxes marked, the built player is unable to connect to the unity profiler. Unity version 2019.4.5f1

**Comment by jamcohen** [comment]
I do see that the "Google -> Build & Run" option doesn't respect the "autoconnect profiler" checkbox. However, it should respect the "development" checkbox.

If you open up the profiler window manually, are you able to connect to the device using the dropdown selector?
<img width="956" alt="Screen Shot 2020-08-28 at 5 23 16 PM 1" src="https://user-images.githubusercontent.com/4805315/91624207-c2530700-e953-11ea-93c9-a5c47a01e9c4.png">

**Comment by TutoMikDab** [comment]
@jamcohen Hi, I tried that multiple times, it fails connecting even with development mode turned on.

**Comment by jamcohen** [comment]
Interesting, I'm not running into that issue.
Are you building an instant game?
Are there any asset packs included in your build?

**Comment by TutoMikDab** [comment]
@jamcohen It's not an instant game. Since I am using the Play Asset Delivery system - yes, I am using asset packs. The asset pack is built with Unity's "Asset Bundle Browser" package, and the asset pack delivery mode is set to "Install Time" in the Google -> Android App Bundle -> Asset Delivery Settings menu.

**Comment by TutoMikDab** [comment]
Both Unity's "Android Logcat" package and Android Studio profiler connects to the device successfully, meaning that the issue does not lie with the device (presumably). What's more - I am using the 1.2.0 version of the Play Asset Delivery package, can you confirm you are using the same one to test it on your end?

**Comment by TutoMikDab** [comment]
Also I am using a cable to connect to the device, and it seems you're using wifi as well?

**Comment by TutoMikDab** [comment]
It appears using the Google "Build & Run" option (at least in my case) requires that both the PC and device be connected to the same wifi network, I also had to open 2 ports that Unity uses for to communicate, and double checked that windows defender isn't blocking the Unity editor. However, profiler connection doesn't work when using ADB (cable only connection).
