### ISSUE TITLE
App Bundles - post-build callback

### ISSUE THREAD

**Issue by WI-Lee** [google/play-unity-plugins#41]
Hi,

When calling `BundleTool.BuildBundle` to build, it returns when the bundle starts building (when the background thread is started) rather than when it has finished building. This means we have no way of knowing when the build is actually finished, and can't automate any post-build steps (e.g. generating APKs).

I noticed there is already a synchronous build path that is used for batch mode builds. Is it possible to expose this for non-batch mode usage? If not, is it possible to add a callback for when the build finishes that we can use to run post-build steps.

Thanks

**Comment by jamcohen** [comment]
Hi @WI-Lee, you raise a great point. I've added this feature request to our internal issue tracker.

**Comment by JurjenBiewenga** [comment]
Any update on this?

**Comment by khliuMagnopus** [comment]
Same here. Is there any updates on this ticket?

**Comment by thanwah** [comment]
Working on this now. Planning to provide both a "force synchronous build" option and a post-build callback (maybe invoked for successful builds only).

**Comment by thanwah** [comment]
The Bundletool class at head now has a couple ways to run code after the build.
