### ISSUE TITLE
In-App Review Quota?

### ISSUE THREAD

**Issue by moldovev** [google/play-unity-plugins#42]
Hi, here is my setup for the In-App Review:

I have a button which triggers the In-App Review process. I know it is not the recommended way but for me it's the way that makes sense for my app. 

The current behavior that happens is that the Review dialog shows the first time the user taps the Review button, but it does nothing if the user cancels the review dialog and taps the Review button again. I believe this scenario happens?

"To provide a great user experience, Google Play enforces a quota on how often a user can be shown the review dialog. Because of this, calling a launchReviewFlow method might not always display a dialog. For example, you should not have a call-to-action option (such as a button) to trigger a review as a user might have already hit their quota and the flow won’t be shown, presenting a broken experience to the user." (from here:  https://developer.android.com/guide/playcore/in-app-review#quotas)

1. What is the quota? is it once every 12 hours, once every 3 hours, once per day, etc. ? When does it reset?
2. If there is no dialogue displayed, the code still executes successfully and there is no error. Is there a way for me as a developer to know if the In-App Dialog has not been displayed due to quota limits? What I want to achieve is that if the quota is reached, then I want to open the classical link to the Play Store and let the user review the old fashioned way.

```
private ReviewManager _reviewManager;
 private PlayReviewInfo _playReviewInfo;
 private string errorMessage;

IEnumerator OpenRateGameAPI()
	{
		_reviewManager = new ReviewManager();
		errorMessage = string.Empty;

		Debug.Log("Request ReviewFlow");
		var requestFlowOperation = _reviewManager.RequestReviewFlow();
		yield return requestFlowOperation;
		Debug.Log("RequestFlow result: " +requestFlowOperation.ToString());

		if (requestFlowOperation.Error != ReviewErrorCode.NoError)
		{
			errorMessage = requestFlowOperation.Error.ToString();

			Debug.Log(errorMessage);

			yield break;
		}

		_playReviewInfo = requestFlowOperation.GetResult();


		Debug.Log("Launch Review Flow");
		var launchFlowOperation = _reviewManager.LaunchReviewFlow(_playReviewInfo);		
		yield return launchFlowOperation;
		Debug.Log("LaunchFlow operation: " + launchFlowOperation.ToString());

		_playReviewInfo = null; // Reset the object

		if (launchFlowOperation.Error != ReviewErrorCode.NoError)
		{
			errorMessage = launchFlowOperation.Error.ToString();

			Debug.Log(errorMessage);
			yield break;
		}

		Debug.Log("RateApi Complete");
	}
```

This is the Logcat of the above code, maybe it helps.

![image](https://user-images.githubusercontent.com/70377421/91561945-0c80bc00-e945-11ea-8c4f-d7fe3889f8ae.png)

**Comment by binouze** [comment]
Hi, same for me, I present an in game popup to ask if the user wants to rate my app before starting the review process.
If nothing happens when the user click on the rate button, the game seems broken.
It would be good to know if the in app review is really show, this way I could fallback to the play store link if it isn't.

**Comment by rafanoel** [comment]
@moldovev please check out [this](https://medium.com/googleplaydev/demystifying-the-new-play-in-app-review-api-1a78e351db7a) blog post, it might clear things out about the quota and not using a button.
