### ISSUE TITLE
In app review - Comment is not optional 

### ISSUE THREAD

**Issue by neslo** [google/play-unity-plugins#44]
Based on the example in 

https://android-developers.googleblog.com/2020/08/in-app-review-api.html

It looks like it is optional to leave a comment. But when I test it on my device (internal tester) then a comment is required.

It would be great if there is some option to make a comment optional in the unity implementation.

**Comment by rafanoel** [comment]
The review is `required` when using internal testing (also for alpha and beta), but once you release your app to the public, the review will be `optional`.

**Comment by neslo** [comment]
Thanks for the info Rafanoel.
