### ISSUE TITLE
AssetBundle Download Based on Texture Format

### ISSUE THREAD

**Issue by Sortexsvg** [google/play-unity-plugins#46]
I have 6 asset bundles each of size 2MB and all are **install time** delivery.
Each asset bundle has same name and different texture format.

When I download my App from Play Store will all 6 asset bundles will be downloaded or asset bundle of device specific texture format is downloaded?

If asset bundle of device specific texture format is downloaded then will the App Size will include all 6 asset bundles size or only one asset bundle size?

I am using Unity 2018.4.
Play Asset Delivery Version 1.2

**Comment by 4ian** [comment]
> When I download my App from Play Store will all 6 asset bundles will be downloaded or asset bundle of device specific texture format is downloaded?

Only the asset bundles with the format that is the most adapted for the device will be downloaded.

As an example: 
* if you create 3 "Level1AssetBundle", in formats ASTC, ETC2 and ETC1, and 3 "Level2AssetBundle", in formats ASTC, ETC2 and ETC1, the app when downloaded from the PlayStore will include only a single "Level1AssetBundle" and a single "Level2AssetBundle".
* In this example, if your device supports ASTC, you'll get one "Level1AssetBundle" and one "Level2AssetBundle", both in ASTC format.

> If asset bundle of device specific texture format is downloaded then will the App Size will include all 6 asset bundles size or only one asset bundle size?

The app size will be the size of the asset bundles with the format that is used for the device.

Using my previous example: if your device supports ASTC, the size shown in the Play Store will be the size of one "Level1AssetBundle" and one "Level2AssetBundle", both in ASTC format.

**Comment by Sortexsvg** [comment]
Thanks for the information
