### ISSUE TITLE
IN APP REVIEW Exception: Field currentActivity or type signature  not found

### ISSUE THREAD

**Issue by alessandroampala** [google/play-unity-plugins#48]
Hi, I am having trouble implementing in app reviews.
At compile time and runtime (playing the project in the editor), it shows this error:

`Exception: Field currentActivity or type signature  not found
UnityEngine._AndroidJNIHelper.GetFieldID (System.IntPtr jclass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223>:0)
UnityEngine.AndroidJNIHelper.GetFieldID (System.IntPtr javaClass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223>:0)
UnityEngine._AndroidJNIHelper.GetFieldID[ReturnType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223>:0)
UnityEngine.AndroidJNIHelper.GetFieldID[FieldType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223>:0)
UnityEngine.AndroidJavaObject._GetStatic[FieldType] (System.String fieldName) (at <e2fcf4f110424f58ac607d4fd98ed223>:0)
UnityEngine.AndroidJavaObject.GetStatic[FieldType] (System.String fieldName) (at <e2fcf4f110424f58ac607d4fd98ed223>:0)
Google.Play.Common.UnityPlayerHelper.GetCurrentActivity () (at Library/PackageCache/com.google.play.common@1.2.0/Runtime/Scripts/UnityPlayerHelper.cs:32)
Google.Play.Review.Internal.ReviewPlayCoreTaskManager..ctor () (at Library/PackageCache/com.google.play.review@1.2.0/Runtime/Scripts/Internal/ReviewPlayCoreTaskManager.cs:35)
Google.Play.Review.ReviewManager..ctor () (at Library/PackageCache/com.google.play.review@1.2.0/Runtime/Scripts/ReviewManager.cs:29)
AdvertisementManager.PlayStoreReview () (at Assets/Scripts/AdvertisementManager.cs:185)
AdvertisementManager.StoreReview () (at Assets/Scripts/AdvertisementManager.cs:175)
GameManager.Start () (at Assets/Scripts/GameManager.cs:77)`

It seems to be happening in the constructor of ReviewManger, and in particular when trying to get the currentActivity with this line: 
return unityPlayer.GetStatic<AndroidJavaObject>("currentActivity");

I tried to compile a development build for android but I can't even do that because of this error.

EDIT: now it makes me compile, in the editor crashesh on ReviewManger constructor while in the apk build nothing happens. Does it need to be published on PlayStore in order to work properly?

**Comment by rafanoel** [comment]
@alessandroampala thanks for reaching out. 

For the first part, it looks like you were trying to use your local editor instead of an Android device, this API only works on an Android device. It's good that is working now.

For the second part, you got it right, your app needs to be published on the Play Store. It is recommended to use the [internal testing](https://play.google.com/console/about/internal-testing/) track because there isn't a display quota. And once you see it's working, you can confidently release your app to the public.

**Comment by rafanoel** [comment]
@alessandroampala  [here](https://developer.android.com/guide/playcore/in-app-review/test#internal-test-track) are some steps to follow up.

**Comment by alessandroampala** [comment]
Thank you very much. However I think it would be better to write it to the developers page in order to make clear that executing this code in the editor will result in an exception.

**Comment by rafanoel** [comment]
Thanks for pointing this up. I will notify the team to take a look at this.
