### ISSUE TITLE
In App Review not showing.

### ISSUE THREAD

**Issue by rafaelf82** [google/play-unity-plugins#49]
I did exactly as listed here:

https://developer.android.com/guide/playcore/in-app-review/unity

I am an internal tester of the app. I did not review the game before. The in app review widget doesn't show up, no error happens, the process reach the end as if everything succeeded but I never see the rating widget.

**Comment by rafanoel** [comment]
Thanks for reaching out. Could you please check if you are using your corp account? If so, please try with a gmail account.

**Comment by rafaelf82** [comment]
> Thanks for reaching out. Could you please check if you are using your corp account? If so, please try with a gmail account.

Ok I had to completely remove my corp account from the device and add a personal account as internal tester, then reinstall the game and I finally got the widget to appear, thank you!
