### ISSUE TITLE
[Play Billing] How to validate Subscriptions

### ISSUE THREAD

**Issue by bilck** [google/play-unity-plugins#50]
What is the proper way to validate subscriptions on a Unity client?

I ask this because according to [Google Play Billing Library documentation](https://developer.android.com/google/play/billing/unity): "_The Google Play Billing plugin does not support using the `SubscriptionManager.UpdateSubscription()` and `SubscriptionManager.UpdateSubscriptionInGooglePlayStore()` methods to upgrade and downgrade your subscriptions. If your game calls these methods, a GooglePlayStoreUnsupportedException is thrown._".

I couldn't find any subscription validation methods on `IGooglePlayStoreExtensions` that replace Unity's SubscriptionManager.

Should I validate it remotely [using this API endpoint](https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptions/get)?
As flawed as it can be, is there an offline method to do that?

**Comment by bilck** [comment]
Ok, so apparently there's no straightforward way to validate a subscription without setting up my own online validation service, right?

Unfortunately seems like the best thing to do is to rollback to regular Unity IAP...

**Comment by Qing451800** [comment]
The implementation of Unity's SubscriptionManager is using a deprecated field called "developerPayload" in Google Play Billing. You can find the deprecation message at: https://developer.android.com/google/play/billing/developer-payload. We didn't add the support of "SubscriptionManager" in our plugin, given this underlying support is deprecated and will be removed some time later.

Server verification will be the most securest way to verify the receipt. If you want to verify the receipt locally, does the CrossPlatformValidator help (https://docs.unity3d.com/Manual/UnityIAPValidatingReceipts.html)?

**Comment by bilck** [comment]
Ok @Qing451800, thanks for the info.

We are already using Unity CrossPlatformValidator but that doesn't give as much information as the Subscription Manager.
