### ISSUE TITLE
Where can we find changelogs for the plugins?

### ISSUE THREAD

**Issue by rafaelf82** [google/play-unity-plugins#58]
I see a update from 1.2.0 to 1.3.0 but can't find what changed on the specific plugin I'm using.

**Comment by thanwah** [comment]
Each package has a CHANGELOG.md file, for example App Bundle's is under [GooglePlayPlugins/com.google.android.appbundle/CHANGELOG.md](https://github.com/google/play-unity-plugins/blob/master/GooglePlayPlugins/com.google.android.appbundle/CHANGELOG.md).

If you're [using Unity 2018.4+ with Game Package Registry](https://developer.android.com/games/develop/build-in-unity#download-registry), you can also view the changelog for each package within Unity Package Manager.

It's possible in limited cases that there may be more information here:

- https://developer.android.com/reference/com/google/android/play/core/release-notes
- https://developer.android.com/google/play/billing/release-notes
