### ISSUE TITLE
The type or namespace name 'GooglePlayStoreModule' does not exist in the namespace 'Google.Play.Billing' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by emaadgh** [google/play-unity-plugins#66]
Hi, I'm trying to Implement Google Play IAP into my Unity project. As [described here](https://developer.android.com/google/play/billing/unity) I Enabled the Unity IAP abstraction layer, Installed Google Play Billing Library, and used Play Billing Build Setting to fix conflicts. 
Now when I use [this script](https://learn.unity.com/tutorial/unity-iap#5c7f8528edbc2a002053b46e) that has been told in the document and then replacing :

 `var builder = ConfigurationBuilder.Instance(StandardPurchasingModule.Instance());` 

with

`var configurationBuilder =
    ConfigurationBuilder.Instance(Google.Play.Billing.GooglePlayStoreModule.Instance());`

I'm getting the following error in Unity Console : 

> Assets\Scripts\Purchaser.cs(59,21): error CS0234: The type or namespace name 'GooglePlayStoreModule' does not exist in the namespace 'Google.Play.Billing' (are you missing an assembly reference?)

I also checked Google.Play.Billing namespace and there is no GooglePlayStoreModule class in it :

![Screenshot 2020-11-09 204247](https://user-images.githubusercontent.com/10380342/98573658-5b938780-22cc-11eb-91c6-803f3875b01e.png)

Unity 2019.4.1f1 LTS
Google Play App Billing Library 3.1.0
Unity IAP (com.unity.purchasing) 2.0.6

**Comment by emaadgh** [comment]
Hi, any update on this? am I missing something?

**Comment by emaadgh** [comment]
The problem was with installing Google Play Billing Library from Unity Package Manager. I just uninstalled it from Package Manager and used the google-play-plugins-1.3.0.unitypackage to import Google Play Plugins and the error is gone.

**Comment by Zeng123m** [comment]
非常好的提问和解决办法，我也是遇到这个问题了。
Very good question and solution, I have the same problem.
