### ISSUE TITLE
Build Play Asset Delivery and missing symbols.zip?

### ISSUE THREAD

**Issue by AlesKriz** [google/play-unity-plugins#68]
When building via Google->Build Android App Bundle button, I do not see symbols.zip in build folder. When I do a build via the Unity->BuildSettings->Build button, the symbols will create it. Is it a bug?

(I have enabled Create symbols.zip in Build Settings)

**Comment by Jes28** [comment]
Google build system builds to temp directory and then copy to actual output dir.
your zipped symbols are there.

We wrote simple post processor that copy symbols to output dir and recompress archive

`
public static class CopySymbolsPostBuild
    {
		public static Boolean 	Aab 		= false;
		public static String 	BuildPath 	= "";
		
        [PostProcessBuild(2_000_000_000)]
        public static void OnPostProcessBuild(BuildTarget target, string pathToBuildProject)
        {
			Debug.Log			( $"[CopySymbolsPostBuild] - OnPostProcessBuild: Aab: {Aab}" );
			
            if (target == BuildTarget.Android)
            {
				var buildDir 	= Path.GetDirectoryName( BuildPath );
				
				if( Aab )
				{
					Debug.Log		( $"[CopySymbolsPostBuild] - OnPostProcessBuild: {pathToBuildProject}" );
					var dir 		= Path.GetDirectoryName( pathToBuildProject );
					Debug.Log		( $"[CopySymbolsPostBuild] - OnPostProcessBuild: temp dir: {dir}" );
					Debug.Log		( $"[CopySymbolsPostBuild] - OnPostProcessBuild: build path: {BuildPath}" );
					Debug.Log		( $"[CopySymbolsPostBuild] - OnPostProcessBuild: build path: {buildDir}" );
					
					foreach ( var zipFile in Directory.EnumerateFiles( dir, "*.zip" ) )
					{
						var toPath 			= Path.Combine( buildDir, Path.GetFileName( zipFile ) );
						Debug.Log			( $"[CopySymbolsPostBuild] - OnPostProcessBuild: Move File: {zipFile} -> {toPath}" );
						File.Move			( zipFile, toPath );
					}
				}
				
				Debug.Log			( $"[CopySymbolsPostBuild] - OnPostProcessBuild: Start repack Symbols" );
				
				var symbolsDir 		= Path.Combine( buildDir, "symbolsUnzipped" );
				
				foreach ( var zipFilePath in Directory.EnumerateFiles( buildDir, "*.zip" ) )
				{
					Debug.Log			( $"[CopySymbolsPostBuild] - OnPostProcessBuild: Extract Zip" );
					ZipFile.ExtractToDirectory( zipFilePath, symbolsDir ) ;
					
					File.Delete( zipFilePath );
					
					Debug.Log			( $"[CopySymbolsPostBuild] - OnPostProcessBuild: Delete And move files" );
					File.Delete( 	Path.Combine( symbolsDir, "arm64-v8a", "libil2cpp.dbg.so" ) );
					File.Move( 		Path.Combine( symbolsDir, "arm64-v8a", "libil2cpp.sym.so" ), 	Path.Combine( symbolsDir, "arm64-v8a", "libil2cpp.so" 	) );
					File.Move( 		Path.Combine( symbolsDir, "arm64-v8a", "libunity.sym.so" ), 	Path.Combine( symbolsDir, "arm64-v8a", "libunity.so" 	) );
					
					Debug.Log			( $"[CopySymbolsPostBuild] - OnPostProcessBuild: Zip back" );
					ZipFile.CreateFromDirectory( symbolsDir, zipFilePath.Replace( "tmp-", "" ), CompressionLevel.Optimal, false );
					
					Debug.Log			( $"[CopySymbolsPostBuild] - OnPostProcessBuild: Done" );
				}
            }
        }
    }
`

**Comment by Xazen** [comment]
Created a fix: https://github.com/google/play-unity-plugins/pull/87

**Comment by thanwah** [comment]
Thank you all for filing this issue and sorry for the delay on a fix. This should now be working [in v1.4.0](https://github.com/google/play-unity-plugins/releases/tag/v1.4.0), but please let me know if you find any issues.
