### ISSUE TITLE
Google Play Instant plugin incorrectly enforces OpenGLES2 requirement

### ISSUE THREAD

**Issue by nilsk123** [google/play-unity-plugins#70]
Hello,

The latest Google Play Instant plugin will only build an AAB if OpenGLES2 is the only graphics api enabled. This requirement is outdated and should be removed, as it prevents apps using ARFoundation from being packed as instant apps

**Comment by thanwah** [comment]
Thanks @nilsk123 for filing this. You're right that this requirement is somewhat outdated since it doesn't apply to instant apps configured to support a minimum version of Android Oreo (API 26) or newer. I'll try to put up a fix this week, though I may not have time to do a full release.

**Comment by thanwah** [comment]
A fix is now committed. As mentioned though, I'm not sure when I'll have time to do a full release containing this change.

**Comment by nilsk123** [comment]
Thanks for looking into it
