### ISSUE TITLE
[Feature Request] Support in-app updates

### ISSUE THREAD

**Issue by Nyankoo** [google/play-unity-plugins#71]
Is it planned to support in-app updates for Unity, like described here?
https://developer.android.com/guide/playcore/in-app-updates

**Comment by YianChen75** [comment]
Now most games provide an in-game update feature, hope Unity can also support this feature as soon as possible.

**Comment by binouze** [comment]
Hi @YianChen75, [this](https://gist.github.com/binouze/a574eee22e08b6ec076cfe594897f191) is a simple implementation of in-app updates that I use on my game. Hope this could helps you

**Comment by thanwah** [comment]
Thanks for filing this feature request. A Play In-App Updates API for Unity is included [in v1.4.0](https://github.com/google/play-unity-plugins/releases/tag/v1.4.0). I'm still working this week on updating the documentation at https://developer.android.com/guide/playcore/in-app-updates.

**Comment by Nyankoo** [comment]
@thanwah Any updates on the documentation update? :)
