### ISSUE TITLE
PlayAssetDelivery.RetrieveAssetBundleAsync() returning the error: Exception: Field currentActivity or type signature  not found

### ISSUE THREAD

**Issue by evertonfd** [google/play-unity-plugins#75]
Hello, it's the first time I'm implementing it, I followed the tutorial for the Demo project and all worked fine.

Now I've copied the part of code that retrieves the asset bundle into my project, selected the folder where my asset bundles are and selected the delivery mode to Fast Follow. What I'm trying to do is: the game starts with a character selection screen, and during the creation of the character it downloads the following scenes in the background.

Here's my code:

```
    public void GetAllSceneBundles()
    {
        var assetBundleQueue = new Queue<string>();

        foreach (string s in sceneBundles)
        {
            assetBundleQueue.Enqueue(s);            
        }
        StartCoroutine(DownloadAssets(assetBundleQueue));
    }

IEnumerator DownloadAssets(Queue<string> assetBundleQueue)
    {
        while (assetBundleQueue.Count > 0)
        {
            string assetBundleName = assetBundleQueue.Dequeue();
            Debug.Log("Getting scene bundle " + assetBundleName);
            PlayAssetBundleRequest bundleRequest =
                    PlayAssetDelivery.RetrieveAssetBundleAsync(assetBundleName);

            AssetDeliveryStatus status = bundleRequest.Status;
            switch (status)
            {
                case AssetDeliveryStatus.Pending:
                    Debug.Log("Asset delivery status pending.");
                    yield return null;
                    break;
                case AssetDeliveryStatus.Retrieving:
                    Debug.Log("Asset delivery status retrieving.");
                    yield return null;
                    break;
                case AssetDeliveryStatus.Available:

                case AssetDeliveryStatus.Loading:
                    Debug.Log("Asset delivery status loading.");
                    yield return null;
                    break;
                case AssetDeliveryStatus.Loaded:
                    assetBundle = bundleRequest.AssetBundle;
                    scenePaths.Add(assetBundle.GetAllScenePaths());
                    Debug.Log("Asset delivery status loaded.");
                    break;
                case AssetDeliveryStatus.Failed:
                    Debug.Log("Asset delivery status failed.");
                    break;
                case AssetDeliveryStatus.WaitingForWifi:
                    Debug.Log("Asset delivery status waiting wi fi.");
                    break;
                default:
                    break;
            }
        }
```

Here follows the details of the error:

Exception: Field currentActivity or type signature  not found
UnityEngine._AndroidJNIHelper.GetFieldID (System.IntPtr jclass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <1b8d7d6285464cff8aa5ccc91decf4f7>:0)
UnityEngine.AndroidJNIHelper.GetFieldID (System.IntPtr javaClass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <1b8d7d6285464cff8aa5ccc91decf4f7>:0)
UnityEngine._AndroidJNIHelper.GetFieldID[ReturnType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <1b8d7d6285464cff8aa5ccc91decf4f7>:0)
UnityEngine.AndroidJNIHelper.GetFieldID[FieldType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <1b8d7d6285464cff8aa5ccc91decf4f7>:0)
UnityEngine.AndroidJavaObject._GetStatic[FieldType] (System.String fieldName) (at <1b8d7d6285464cff8aa5ccc91decf4f7>:0)
UnityEngine.AndroidJavaObject.GetStatic[FieldType] (System.String fieldName) (at <1b8d7d6285464cff8aa5ccc91decf4f7>:0)
Google.Play.Common.UnityPlayerHelper.GetCurrentActivity () (at Assets/GooglePlayPlugins/com.google.play.common/Runtime/Scripts/UnityPlayerHelper.cs:32)
Google.Play.AssetDelivery.Internal.AssetPackManager..ctor () (at Assets/GooglePlayPlugins/com.google.play.assetdelivery/Runtime/Scripts/Internal/AssetPackManager.cs:33)
Google.Play.AssetDelivery.Internal.PlayAssetDeliveryInternal..ctor () (at Assets/GooglePlayPlugins/com.google.play.assetdelivery/Runtime/Scripts/Internal/PlayAssetDeliveryInternal.cs:44)
Google.Play.AssetDelivery.PlayAssetDelivery.get_Instance () (at Assets/GooglePlayPlugins/com.google.play.assetdelivery/Runtime/Scripts/PlayAssetDelivery.cs:32)
Google.Play.AssetDelivery.PlayAssetDelivery.RetrieveAssetBundleAsync (System.String assetBundleName) (at Assets/GooglePlayPlugins/com.google.play.assetdelivery/Runtime/Scripts/PlayAssetDelivery.cs:57)
MapEdge+<DownloadAssets>d__33.MoveNext () (at Assets/Scripts/Travel System/MapEdge.cs:107)

To make it clearer, on the start function of MapEdge it calls GetAllSceneBundles that calls MapEdge.cs:107 , where I finally call PlayAssetBundleRequest bundleRequest =
                    PlayAssetDelivery.RetrieveAssetBundleAsync(assetBundleName); and the fuction stops there, it doesn't even get to the status part.

I'm not an experienced programmer, I've been trying to solve this issue for a couple days, this is what I've already tried:
Updated JDK
Updated NDK
On UnityPlayerHelper tried to create this current activity by adding this code: unityPlayer.SetStatic<AndroidJavaObject>("currentActivity", unityPlayer);
I found this Legacy documentation https://docs.unity3d.com/540/Documentation/Manual/PluginsForAndroid.html and tried to set AndroidJNIHelper.debug = true; 
Build the App Bundle and release on the PlayStore for internal test, but as soon as the first scene loads, right when I get this error on the Editor the app crashes, I've tried building because I saw a post where someone said that for the Editor there's no currentActivity and that's why it should throw this error.

Thanks in advance.

** Just an update, the error was in the 2019.3.15 version, I've updated to 2020.1.16 and the error still applies, now I've tried again with the demo version from the tutorial and I'm getting the same error!

**Comment by jamcohen** [comment]
Hi evertonfd,

I'm sorry you're running into issues.

The currentActivity error that you're seeing is indeed caused by running PlayAssetDelivery methods in the Editor. To diagnose the app crash you want to look at the logs generated on device using [`adb logcat`](https://developer.android.com/studio/command-line/logcat).

My guess from looking at the code is that your `DownloadAssets` coroutine is calling `PlayAssetDelivery.RetrieveAssetBundleAsync(assetBundleName)` every frame. `RetrieveAssetBundleAsync` will throw an exception if an assetBundle request already exists with that name. You should wrap your switch statement in a while loop, so that it only calls `PlayAssetDelivery.RetrieveAssetBundleAsync(assetBundleName)` once per assetBundleName.

Example:
````
IEnumerator DownloadAssets(Queue<string> assetBundleQueue)
{
    while (assetBundleQueue.Count > 0)
    {
        string assetBundleName = assetBundleQueue.Dequeue();
        Debug.Log("Getting scene bundle " + assetBundleName);
        PlayAssetBundleRequest bundleRequest =
                PlayAssetDelivery.RetrieveAssetBundleAsync(assetBundleName);

        AssetDeliveryStatus status = bundleRequest.Status;
        while(status != AssetDeliveryStatus.Failed && status != AssetDeliveryStatus.Loaded)
        {
            switch (status)
            {
                case AssetDeliveryStatus.Pending:
                    Debug.Log("Asset delivery status pending.");
                    yield return null;
                    break;
                case AssetDeliveryStatus.Retrieving:
                    Debug.Log("Asset delivery status retrieving.");
                    yield return null;
                    break;
                case AssetDeliveryStatus.Available:

                case AssetDeliveryStatus.Loading:
                    Debug.Log("Asset delivery status loading.");
                    yield return null;
                    break;
                case AssetDeliveryStatus.Loaded:
                    assetBundle = bundleRequest.AssetBundle;
                    scenePaths.Add(assetBundle.GetAllScenePaths());
                    Debug.Log("Asset delivery status loaded.");
                    break;
                case AssetDeliveryStatus.Failed:
                    Debug.Log("Asset delivery status failed.");
                    break;
                case AssetDeliveryStatus.WaitingForWifi:
                    Debug.Log("Asset delivery status waiting wi fi.");
                    yield return null;
                    break;
                default:
                    break;
            }
        }
    }
}
````

**Comment by evertonfd** [comment]
Hello, thanks for the reply.

I tried adb logcat, but from what I understood, it sent a log to a file that I couldn't find in my computer, here follows what I believe is the useful output:

12-10 07:14:40.926   756   800 I Unity   : Exception : System.IO.IOException: Write failure ---> System.Net.Sockets.SocketException: The socket has been shut down
12-10 07:14:40.926   756   800 I Unity   :   at System.Net.Sockets.Socket.Send (System.Byte[] buf, Int32 offset, Int32 size, SocketFlags flags) [0x00000] in <filename unknown>:0
12-10 07:14:40.926   756   800 I Unity   :   at System.Net.Sockets.NetworkStream.Write (System.Byte[] buffer, Int32 offset, Int32 size) [0x00000] in <filename unknown>:0
12-10 07:14:40.926   756   800 I Unity   :   --- End of inner exception stack trace ---
12-10 07:14:40.926   756   800 I Unity   :   at System.Net.Sockets.NetworkStream.Write (System.Byte[] buffer, Int32 offset, Int32 size) [0x00000] in <filename unknown>:0
12-10 07:14:40.926   756   800 I Unity   :   at Utils.CopyToStream (System.IO.Stream src, System.IO.Stream dst, System.Byte[] buffer, Int32 numBytes) [0x00000] in <filename unknown>:0
12-10 07:14:40.926   756   800 I Unity   :   at RemoteConnection.ProcessOutgoingData () [0x00000] in <filename unknown>:0
12-10 07:14:40.926   756   800 I Unity   :   at RemoteConnection.Update () [0x00000] in <filename unknown>:0
12-10 07:14:40.926   756   800 I Unity   :
12-10 07:14:40.926   756   800 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

The other problem is that the function is called only once, I updated as you recommended and added a debug log to check the calls:
 `
while (assetBundleQueue.Count > 0)
 {
            string assetBundleName = assetBundleQueue.Dequeue();
            Debug.Log("Getting scene bundle " + assetBundleName);
            PlayAssetBundleRequest bundleRequest =
                    PlayAssetDelivery.RetrieveAssetBundleAsync(assetBundleName);
            Debug.Log("Passed the request.");
...
`

But it never gets to the "Passed the request", here follows a print from my console:

![error](https://user-images.githubusercontent.com/30388054/101729213-15426b80-3ab8-11eb-9c8e-7ad735bfa55d.png)

**Comment by jamcohen** [comment]
`PlayAssetDelivery.RetrieveAssetBundleAsync()` is designed to be run only on the Android device, and will always throw that Exception when it is run in the Editor.

When you run "adb logcat", do you see the "Getting scene bundle" log?

**Comment by evertonfd** [comment]
No, I don't, it actually doesn't change much, I've tried placing this function on a button to trigger only later but nothing works, any function I call from the `PlayAssetDelivery` crashes the whole Class and stops any further code, I've tried `while (!PlayAssetDelivery.IsDownloaded(assetBundleName))`, but it crashes when it's called, I've tried `PlayAssetDelivery.GetDownloadSize`, but it also crashes, it seems that I'm calling a function that was not initialized, or something like that, but I've added `using Google.Play.AssetDelivery;`, I really don't know what to do, I've checked again the tutorial but got no further enlightment...

**Comment by jamcohen** [comment]
It's strange that you aren't seeing the "Getting scene bundle" log, since that runs right before the PlayAssetDelivery method. I was hoping to isolate the crash log by looking for logs after "Getting scene bundle".

To clarify, when you say that the class is crashing, do you mean that the app on your Android device is crashing? As in, the app quits? Or does the app freeze but remain on screen?

You mention that you're calling a function that was not initialized. Was there something in the logcat that led you to that conclusion?

Could you try running the code I recommended on device and then sending a [bugreport](https://developer.android.com/studio/debug/bug-report) to play-unity-plugin-support@googlegroups.com. That might point me to the source of the crash.

If you're comfortable sharing your project, or some subset of your project that reproduces the issue, you can send the project to that support email and I can try to reproduce the issue.

**Comment by evertonfd** [comment]
Hello, I'll profit that you've answered a few minutes ago: 
When I run the adb logcat the only thing I see different is what I posted before, there's nothing after that.
If I run on my android device the build I have on my internal test the app freeze and close, I can share the build with you or add you to the internal test list. When I run the app in my Android using the UnityRemote it runs regularly, but the function doesn't work, as I get the error described on the tittle of this thread.
When I say that it seems that the function has not been initialized is because every time I call the function on the editor, I get the error and the application don't run the rest of the code inside that class, the execution actually stops right there, no matter which function inside the PlayAssetDelivery I call.

**Comment by jamcohen** [comment]
PlayAssetDelivery methods call into an Android plugin that only works when running on an Android device. Otherwise they will throw the `type signature not found` exception. Using UnityRemote doesn't actually run the app on Android. It runs the app in the editor and streams the visual output to your device. That's why you're also seeing the exception when using UnityRemote.

It would be great if you could add my test account (jakecohen.test@gmail.com) to your internal testers list and send a link with the build to that email.

Thanks!

**Comment by evertonfd** [comment]
Thanks!
I've added you and sent you the link by email.
I was trying the adb logcat with the editor, now I've tried with the app and it comes a completely different result, sorry for my ignorance.... This is what I found about async operation:

12-11 21:23:22.246 19912 19936 I Unity   : System.Action`1:Invoke(T)
12-11 21:23:22.246 19912 19936 I Unity   : UnityEngine.AsyncOperation:InvokeCompletionEvent()
12-11 21:23:22.246 19912 19936 I Unity   :
12-11 21:23:22.246 19912 19936 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
12-11 21:23:22.246 19912 19936 I Unity   :
12-11 21:23:22.275 18754 18849 D vndksupport: Loading /vendor/lib/hw/gralloc.msm8937.so from current namespace instead of sphal namespace.
12-11 21:23:22.288 18754 18849 I Adreno  : PFP: 0x005ff087, ME: 0x005ff063
12-11 21:23:22.291 18754 18849 I zygote  : android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
12-11 21:23:22.293 18754 18849 I OpenGLRenderer: Initialized EGL, version 1.4
12-11 21:23:22.293 18754 18849 D OpenGLRenderer: Swap behavior 2
12-11 21:23:22.344 19912 19967 E Swappy::EGL: Failed to get sync status
12-11 21:23:22.344 19912 19967 E Swappy::EGL: Failed to destroy sync fence
12-11 21:23:22.344  2533  7064 I ActivityManager: Process com.google.process.gapps (pid 19423) has died: cch+6CEM
12-11 21:23:22.352  2533  2557 W zygote  : kill(-19423, 9) failed: No such process
12-11 21:23:22.378  2533  2557 W zygote  : kill(-19423, 9) failed: No such process
12-11 21:23:22.378  2533  2557 I zygote  : Successfully killed process cgroup uid 10025 pid 19423 in 26ms
12-11 21:23:22.395 19912 19972 E Swappy::EGL: Timeout waiting for fence
12-11 21:23:22.429 18754 18774 W ProxyAndroidLoggerBackend: Too many Flogger logs received before configuration. Dropping old logs.
12-11 21:23:22.430 18754 18774 I chatty  : uid=10049(com.android.vending) BlockingExecuto identical 1 line
12-11 21:23:22.551 18754 18774 W ProxyAndroidLoggerBackend: Too many Flogger logs received before configuration. Dropping old logs.
12-11 21:23:22.560 18754 18793 I Finsky  : [16520] zzi.c(1): Regular flags synced
12-11 21:23:22.568 18754 18793 I Finsky  : [16520] zyg.b(3): Writing flags config, size 1.
12-11 21:23:22.569 18754 18793 I Finsky  : [16520] zyg.b(3): Started writing experiment flags into file [4dEVOh7DlClE42ly_19Hs7FqnnFOj9O0dm-zzWqGxeo].
12-11 21:23:22.577 18754 18764 I zygote  : Background concurrent copying GC freed 211982(8MB) AllocSpace objects, 15(1288KB) LOS objects, 49% free, 10MB/21MB, paused 395us total 229.637ms
12-11 21:23:22.613  2533  2900 I InputReader: Reconfiguring input devices.  changes=0x00000004
12-11 21:23:22.613  2533  2900 I InputReader: Device reconfigured: id=5, name='synaptics_dsx_i2c', size 1080x1920, orientation 1, mode 1, display id 0
12-11 21:23:22.614  2533  2900 I InputReader: Reconfiguring input devices.  changes=0x00000004
12-11 21:23:22.643  2533  2573 I ActivityManager: Config changes=480 {1.0 222mcc50mnc [en_US,it_IT,pt_BR] ldltr sw360dp w592dp h336dp 480dpi nrml land finger -keyb/v/h -nav/h appBounds=Rect(0, 0 - 1776, 1080) s.196 spniliad gidf003}
12-11 21:23:22.686  2533  2573 I ActivityManager: Override config changes=480 {1.0 222mcc50mnc [en_US,it_IT,pt_BR] ldltr sw360dp w592dp h336dp 480dpi nrml land finger -keyb/v/h -nav/h appBounds=Rect(0, 0 - 1776, 1080) s.196 spniliad gidf003} for displayId=0

**Comment by jamcohen** [comment]
Thanks for sending over the app.

Could you share the lines above the `UnityEngine.AsyncOperation:InvokeCompletionEvent()` log? The actual error should be a couple lines above it.

**Comment by evertonfd** [comment]
Sure, here follows>

12-11 23:04:14.460  2533  8636 I ActivityManager: Start proc 25372:com.android.chrome:sandboxed_process0/u0i321 for webview_service com.BeorGames.Revenot/org.chromium.content.app.SandboxedProcessService0
12-11 23:04:14.460 25372 25372 E Zygote  : createProcessGroup(99321, 0) failed: Permission denied
12-11 23:04:14.564 21200 21200 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.safetynet.service.START pkg=com.google.android.gms }
12-11 23:04:14.565 21200 21200 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.safetynet.service.START pkg=com.google.android.gms }
12-11 23:04:14.672 25392 25392 E asset   : setgid: Operation not permitted
12-11 23:04:14.837 25372 25372 I cr_ChildProcessService: Creating new ChildProcessService pid=25372
12-11 23:04:14.975 25232 25263 I Unity   : Fetching show updates as False
12-11 23:04:14.975 25232 25263 I Unity   : UnityEngine.Logger:Log(LogType, Object)
12-11 23:04:14.975 25232 25263 I Unity   : RemoteConfigManager:ApplyRemoteSettings(ConfigResponse)
12-11 23:04:14.975 25232 25263 I Unity   : System.Action`1:Invoke(T)
12-11 23:04:14.975 25232 25263 I Unity   : Unity.RemoteConfig.ConfigManager:OnRawResponseReturned(ConfigOrigin, Dictionary`2, String)
12-11 23:04:14.975 25232 25263 I Unity   : System.Action`3:Invoke(T1, T2, T3)
12-11 23:04:14.975 25232 25263 I Unity   : Unity.RemoteConfig.<>c__DisplayClass34_0:<PostConfig>b__0(AsyncOperation)
12-11 23:04:14.975 25232 25263 I Unity   : System.Action`1:Invoke(T)
12-11 23:04:14.975 25232 25263 I Unity   : UnityEngine.AsyncOperation:InvokeCompletionEvent()
12-11 23:04:14.975 25232 25263 I Unity   :
12-11 23:04:14.975 25232 25263 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
12-11 23:04:14.975 25232 25263 I Unity   :
12-11 23:04:15.063 25232 25310 E Swappy::EGL: Timeout waiting for fence


If you manage to play the game let me know also

Thanks again

**Comment by jamcohen** [comment]
Hmm that log doesn't look like the cause of the cause. When I play the game on internal testing, I see [these logs](https://github.com/google/play-unity-plugins/files/5681895/logcat-rev.txt).

A couple logs that stand out:
1. 
````
ArgumentException: There is already an active request for AssetBundle: s
````

That's the issue I mentioned in my first comment. Try to only call `RetrieveAssetBundleAsync` once and see if that gets rid of the crash.

2. 
````
12-11 15:42:56.810 18695 18721 I UnityIAP: Starting in-app billing setup.
12-11 15:42:56.817 18695 18721 E Unity   : NullReferenceException: Object reference not set to an instance of an object.
12-11 15:42:56.817 18695 18721 E Unity   :   at Hotkey.OnPotionChanged (Consumable potChangedConsumable) [0x00000] in <00000000000000000000000000000000>:0
12-11 15:42:56.817 18695 18721 E Unity   :   at Hotkey.UpdateKey (Skill sk, Buff bf, Consumable cn) [0x00000] in <00000000000000000000000000000000>:0
12-11 15:42:56.817 18695 18721 E Unity   :   at HotkeyManager.SelectKey (System.Int32 key) [0x00000] in <00000000000000000000000000000000>:0
12-11 15:42:56.817 18695 18721 E Unity   :   at HotkeyManager.LoadConsumableKeys () [0x00000] in <00000000000000000000000000000000>:0
12-11 15:42:56.817 18695 18721 E Unity   :   at HotkeyManager+<UpdateConsumables>d__10.MoveNext () [0x00000] in <00000000000000000000000000000000>:0
12-11 15:42:56.817 18695 18721 E Unity   :   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0
````

This is a null reference exception that occurs right after UnityIAP starts its setup. It is possible that this exception interrupts UnityIAP's setup process and leads to the below exception that crashes the app. 

3.
````
--------- beginning of crash
12-11 15:42:56.840 18695 18789 E AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
12-11 15:42:56.840 18695 18789 E AndroidRuntime: Process: com.BeorGames.Revenot, PID: 18695
12-11 15:42:56.840 18695 18789 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/vending/billing/IInAppBillingService$Stub;
12-11 15:42:56.840 18695 18789 E AndroidRuntime: 	at com.unity.purchasing.googleplay.BillingServiceManager$1$2.run(BillingServiceManager.java:85)
12-11 15:42:56.840 18695 18789 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-11 15:42:56.840 18695 18789 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-11 15:42:56.840 18695 18789 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
12-11 15:42:56.840 18695 18789 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.android.vending.billing.IInAppBillingService$Stub
12-11 15:42:56.840 18695 18789 E AndroidRuntime: 	... 4 more
````

This is the exception that is causing the app to crash. It looks relating to Unity's in-app purchasing. You can try disabling in-app purchasing and see if the app still crashes.

My guess is that the exception thrown in 1 prevents some reference from being set in HotkeyManager. Then, HotkeyManager throws exception 2 which messes with some UnityIAP setup, which causes exception 3.

My recommendation would be to try the following on device (not in the editor, or with UnityRemote):
1. Remove all references to PlayAssetDelivery and see if the crashes go away. If the app is still crashing, then the issue is being caused by something else.
2. Try calling `RetrieveAssetBundleAsync` just once and see if you can download a pack successfully. If that works, then look at your code and try to prevent your code from calling `RetrieveAssetBundleAsync` twice with the same assetBundleName.

To test on device, I recommend uploading your asset bundle using [internal sharing](https://support.google.com/googleplay/android-developer/answer/9844679?_ga=2.46094628.14525272.1607727245-164188110.1598400598). Or you can use Google -> Build & Run app bundle in the Unity menu bar.

Let me know if any of that helps.

**Comment by evertonfd** [comment]
I've finally figured out! 10 days after the first problem!! 

At the end there was nothing to do specifically with the `RetrieveAssetBundleAsync()` function, the real problem that was preventing me to play the game was actually when I installed the Google package, there's this option under Google > Play Billing > Build Settings
![billing](https://user-images.githubusercontent.com/30388054/102395820-ed816500-3fdb-11eb-975f-b40cad4bc98c.png)

If I click Fix than I have the problem that the game will build, but crash at start. It's so counter intuitive, since the pop up window tells you that this is going to happen if you don't click fix...

**Comment by evertonfd** [comment]
Thank you very much, the problem is solved, not actually what we thought it was, but at least the game is working now.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
