### ISSUE TITLE
Google.Review window not appearing

### ISSUE THREAD

**Issue by KealoNL** [google/play-unity-plugins#83]
Hello,

After days of debugging, hooking up adb to the testphones, trying out different phones im really in a point where i dont think its anything on my end.

Current code:

private IEnumerator ReviewCoroutine()
    {
        var requestFlowOperation = _reviewManager.RequestReviewFlow();
        yield return requestFlowOperation;
            if (requestFlowOperation.Error != ReviewErrorCode.NoError)
            {
                Application.OpenURL("https://play.google.com/store/apps/details?id=com.BigBangStudio.Pebbles");
                yield break;
            }
        _playReviewInfo = requestFlowOperation.GetResult();
        var launchFlowOperation = _reviewManager.LaunchReviewFlow(_playReviewInfo);
        yield return launchFlowOperation;

        _playReviewInfo = null;

        if (launchFlowOperation.Error != ReviewErrorCode.NoError)
            {
                Application.OpenURL("https://play.google.com/store/apps/details?id=com.BigBangStudio.Pebbles");
                yield break;
            }

            else if (launchFlowOperation.Error == ReviewErrorCode.NoError && !UserProgress.Current.HasGivenFeedback)
            {
                UserProgress.Current.Coins += reviewCoinValue;
                UserProgress.Current.HasGivenFeedback = true;
            }
    }

Test device is a new out of the box phone, new gmail account, not linked to business whatsoever, tried all debugging options and fixes on this issue list. Id love to get some help on this matter.

**Comment by rafanoel** [comment]
Have you tried using the [internal testing track](https://play.google.com/console/about/internal-testing/)?

On this track, you should be able to launch the review every time the review flow is called.

**Comment by KealoNL** [comment]
Hello rafanoel, yes both internal, and production. Both not providing the window.

**Comment by rafanoel** [comment]
Unfortunately, in prod, it won't show every time the review flow is called, that's why you need to be on internal testing track or app sharing (which provides a direct link to download the app).

If you have been working on multiple tracks, you could try clearing the storage of the Play Store.

**Comment by KealoNL** [comment]
But that's incredibly strange right? I want to show my users in production that it launches? How come it partially works in that track. With Production I mean the actual store/release

**Comment by KealoNL** [comment]
My god, it was the cache for my main test phone. Today I will try with multiple other test devices. Would be great if this 'hidden' step would be documented. Incredibly hard to debug this way.

**Comment by rafanoel** [comment]
Glad to hear that it's working.

As a note, in prod, the showing of the review is driven by a quota, there is some explanation of this and other common questions [here] (https://medium.com/googleplaydev/demystifying-the-new-play-in-app-review-api-1a78e351db7a).
