### ISSUE TITLE
Play Instant + Asset Bundle Delivery Integration

### ISSUE THREAD

**Issue by moldovev** [google/play-unity-plugins#85]
HI, 

I am a bit confused about how the following things should work together.
Here is my scenario: 

I have created an Instant version of my game (apk 14.5 MB) that uses 3 asset bundles (3 mb, 3mb, 10 mb) to fetch the game resources. This is allowed as per:
https://developer.android.com/topic/google-play-instant/instant-play-games-checklist#requirements
![image](https://user-images.githubusercontent.com/70377421/107556544-38d18180-6be1-11eb-982e-228208ecb566.png)

Now the only way to pack these asset bundles into my app bundle is by having them marked as "on-demand". The other 2 values, install time and fast-follow are not allowed for instant apps, as per plugin messages
![image](https://user-images.githubusercontent.com/70377421/107556493-26574800-6be1-11eb-9fab-fffcbb9a7802.png)

now, as per step 13 form the same link
"Specify 1337 as the instant flavor in your AndroidManifest.xml file to indicate that this is a full-experience Instant play game (and not a trial game):" - this is done by the Play Instant Plugin if you mark "Full instant Play Game".

But if I do that, then I get a message that I cannot have Asset Bundles in a Full Game.

So the only way to make my game work is having Asset Bundles on-demand and Full Game Unchecked.

However, as per Rule (1), I am allowed to download Asset Bundles. But then my FULL GAME from a content-delivery point of view is marked as "Trial", even though it is not.

I also stumbled upon this documentation
https://developer.android.com/topic/google-play-instant/feature-module-migration#feature_module_to_dynamic_feature
plus this
https://developer.android.com/topic/google-play-instant/getting-started/cloud-delivery-assets#play_feature_delivery_through_app_bundles
which adds to my confusion. dist:instant="true" and dist:onDemand="false" in the module’s manifest? Does this apply to Unity? If so, where? Is this some missing functionality from the Unity Instant Plugin, or is there something else I am missing? 
What is the correct way to deliver my instant full game that has additional asset bundles downloaded at startup?

Thanks,
- Victor

**Comment by jamcohen** [comment]
Hi moldovev,

Thanks for the detailed post.

In this case you can feel free to submit your game with the "Full instant Play Game" option unchecked. Once you fill out the form [here](https://developer.android.com/topic/google-play-instant/instant-play-games-checklist#submit) someone from the play games team will reach out to you. Let them know that you're using on-demand asset packs and thus couldn't change the manifest flavor. They'll help you work around that requirement.

You shouldn't need to worry about setting the dist:instant and dist:onDemand values manually. If you build the instant app with "Google -> Build Android App Bundle" those values will be set properly based on the "Android Build Type" in "Play Instant Build Settings"

Best,
Jake

**Comment by moldovev** [comment]
Hi Jake, 

Thanks for clearing things out; now I know I did the right steps. 
I will reach out to the play games team, as suggested.

Thanks!

**Comment by isrmicha** [comment]
It's possible to reach nowdays with Unity 2021.3+ less than 15mb android apk build ?
