### ISSUE TITLE
Proper way to load an AB contained in an asset pack which has multiple ABs.

### ISSUE THREAD

**Issue by sueh** [google/play-unity-plugins#9]
We have a sample project to illustrate the usage of Dynamic Asset Delivery, however we cannot find a proper way to load AB bundled as follow:

1. We have two ABs in a same directory: cube.ab and box.ab which contains a single prefab separately.
2. An AssetPackConfig is created and the two ABs are added via calling AddAssetsFolder method provided their containg directory. We name the asset pack Sample_AAB_AssetPack.
3. Build an AAB with the configuration and installed to a device.
4. Load a AB via calling RetrieveAssetBundleAsync method provided name of the AB (e.g. cube). An error occurred.

From logcat we get this error message:

Unity   : Failed to retrieve AssetBundle No APKs available for pack 'cube'.:
Unity   : Google.Play.AssetDelivery.Internal.<>c__DisplayClass8_1:<RetrieveAssetBundleAsyncInternal>b__1(String, Int32)
Unity   : System.Action`2:Invoke(T1, T2)
Unity   : System.Action:Invoke()
Unity   : Google.Play.Core.Internal.PlayCoreEventHandler:Update()
Unity   :
Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)
Unity   :
Unity   : Couldn't load AssetBundles: InternalError
Unity   : Google.Play.AssetDelivery.Samples.AssetDeliveryDemo.<DownloadAssetBundleCo>d__35:MoveNext()
Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
Unity   :
Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Thanks in advance.

**Comment by jamcohen** [comment]
Thank you for bringing up this issue. We realize there's some inconsistencies between the packaging API and the runtime API (e.g. RetrieveAssetBundleAsync). We're exploring resolving these inconsistencies but currently, the runtime API only supports one AssetBundle per asset pack. It also assumes that the name of the pack matches the name of the AssetBundle. So in this case you would need two have two asset packs, named cube and box, each containing their own respective AssetBundle.

**Comment by sueh** [comment]
OK, looking forward to fix these inconsistencies. As in our real projects there are thousands of ABs, a one to one mapping cannot be made with asset pack number upper limit set. Thanks for you guys' greate work.

**Comment by jamcohen** [comment]
Update: We added experimental support for this in the v1.1.1 release. 

You can now use the [RetrieveAssetPackAsync()](https://github.com/google/play-unity-plugins/blob/d518e6f300615952320e34396b4ef82404cb8a36/GooglePlayPlugins/com.google.play.assetdelivery/Runtime/Scripts/PlayAssetDelivery.cs#L67) method to download an asset pack  with arbitrary contents.

If you want to give it a try, you can enable the PLAY_ASSET_DELIVERY_EXPERIMENTAL preprocessor definition in player settings (see the "Platform custom #defines" section here for how to do that)
